- README.md
- manifests/configmap.yaml
- manifests/fake-teams-api.yaml
- manifests/postgres-operator.yaml
ref https://github.com/zalando-incubator/postgres-operator/issues/2
> Make use of the local fake teams api

- Makefile
> #10 fix make docker

- README.md
Readers should see the whole flow and know how to connect to their new test cluster in Minikube :smile:
> README: how to connect via psql

- pkg/cluster/cluster.go
- pkg/cluster/k8sres.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
- pkg/controller/postgresql.go
- pkg/spec/postgresql.go
— Ignore clusters with wrong specification
— catch quantity parsing errors
> Skip invalid clusters

- pkg/cluster/cluster.go
- pkg/util/config/util.go
here are some details: https://goreportcard.com/report/github.com/zalando-incubator/postgres-operator#go_vet
> Fix issues found by go vet

- pkg/cluster/cluster.go
- pkg/cluster/resources.go
go vet found that there is a return command is missing
> Add missed return

- pkg/cluster/cluster.go
- pkg/cluster/k8sres.go
- pkg/cluster/pg.go
- pkg/cluster/pod.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
- pkg/cluster/util.go
- pkg/controller/controller.go
- pkg/controller/etcd.go
- pkg/controller/postgresql.go
- pkg/controller/util.go
- pkg/spec/postgresql.go
- pkg/spec/types.go
- pkg/util/config/config.go
- pkg/util/constants/constants.go
- pkg/util/k8sutil/k8sutil.go
- pkg/util/teams/teams.go
- pkg/util/users/users.go
- pkg/util/util.go
Fix the warnings found by golint tool
> Fix the golint warnings

- pkg/cluster/sync.go
> Don't error out at sync on existence of the object.

- Makefile
- Re-introduce -i flag for Mac OS
- Remove binary dependencies for builds to allow re-building w/o make
clean
> Small Makefile improvements.

- pkg/cluster/cluster.go
- pkg/cluster/pod.go
- pkg/cluster/sync.go
- pkg/controller/pod.go
- pkg/controller/postgresql.go
- pkg/spec/types.go
Make use of the FIFO queue for the pod events of the cluster
> Use queues for the pod events

- pkg/cluster/cluster.go
- pkg/cluster/filesystems.go
- pkg/cluster/pg.go
- pkg/cluster/volumes.go
- pkg/controller/controller.go
- pkg/controller/postgresql.go
- pkg/util/k8sutil/k8sutil.go
- pkg/util/teams/teams.go
- pkg/util/teams/teams_test.go
https://github.com/dominikh/go-tools/tree/master/cmd/errcheck-ng
> Add error checks per report from errcheck-ng

- manifests/configmap.yaml
- pkg/controller/controller.go
- pkg/controller/postgresql.go
- pkg/util/config/config.go
- pkg/util/constants/kubernetes.go
Run sync not oftener than resync_period interval.
Periodically run resync of the clusters
> Fix resync of clusters

- pkg/cluster/cluster.go
- pkg/cluster/sync.go
- pkg/cluster/volumes.go
- pkg/spec/postgresql.go
- pkg/spec/postgresql_test.go
- pkg/util/teams/teams.go
- pkg/util/util_test.go
remove unnecessary tests;
go fmt -s
> Fix goreport warnings

- pkg/controller/controller.go
> Remove an unused export.

- .travis.yml
> A bare bones .travis.yml

- .travis.yml
- README.md
> Add a few badges

- delivery.yaml
Do push as postgres-operator from the master branch, and as a
postgres-operator-test when evaluating pull-requests.
> Avoid pushing postgres-operator image on PRs.

- pkg/util/config/config.go
Skip config params which have neither default nor user value
> Skip config params with no values

- pkg/controller/postgresql.go
Fix eventually broken cluster event queue processing
> Fix cluster event queue processing

- pkg/cluster/cluster.go
- pkg/cluster/exec.go
- pkg/cluster/k8sres.go
- pkg/cluster/pg.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
- pkg/cluster/types.go
- pkg/cluster/util.go
- pkg/cluster/volumes.go
- pkg/controller/controller.go
- pkg/controller/postgresql.go
- pkg/controller/util_test.go
- pkg/spec/types.go
- pkg/util/config/config.go
- pkg/util/constants/aws.go
- pkg/util/constants/postgresql.go
- pkg/util/constants/roles.go
- pkg/util/filesystems/ext234.go
- pkg/util/filesystems/filesystems.go
- pkg/util/k8sutil/k8sutil.go
- pkg/util/retryutil/retry_util.go
- pkg/util/teams/teams.go
- pkg/util/teams/teams_test.go
- pkg/util/util.go
- pkg/util/volumes/ebs.go
- pkg/util/volumes/volumes.go
Fix the warnings generated by [gometalinter](https://github.com/alecthomas/gometalinter)
> Fix some golint warnings

- pkg/cluster/k8sres.go
https://github.com/zalando-incubator/postgres-operator/issues/76
> Fix missing labels in the replica service selector.

- pkg/util/config/config.go
fix pam_role_name parameter name.
> fix pam_role_name parameter name.

- pkg/cluster/pg.go
- pkg/util/config/config.go
Set DB connection to nil upon closing it.
> Avoid reusing closed DB connection.

- manifests/configmap.yaml
- pkg/apiserver/apiserver.go
- pkg/cluster/cluster.go
- pkg/cluster/resources.go
- pkg/controller/controller.go
- pkg/controller/postgresql.go
- pkg/controller/status.go
- pkg/spec/types.go
- pkg/util/config/config.go
- pkg/util/ringlog/ringlog.go
- pkg/util/util.go
- pkg/util/util_test.go
Diagnostic REST API provides profiling data via pprof, cluster and worker logs, cluster and controller statuses and configuration.
> Diagnostic API

- pkg/cluster/cluster.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
- pkg/cluster/util.go
- pkg/controller/postgresql.go
- pkg/util/util.go
Make cluster event queue non-blocking, so that we can dump the queue via API;
Rename Service field to the Services as it contains multiple objects;
Remove var shading
> Fix cluster event queue consumption

- manifests/configmap.yaml
- pkg/cluster/k8sres.go
- pkg/util/config/config.go
Allow setting pod termination period in the config map
> Make pod termination grace period configurable

- pkg/apiserver/apiserver.go
- pkg/cluster/cluster.go
- pkg/cluster/k8sres.go
- pkg/cluster/pg.go
- pkg/cluster/resources.go
- pkg/controller/util.go
> Use warningf instead of warnf

- pkg/cluster/cluster.go
- pkg/util/patroni/patroni.go
currently patroni api client has only one method — failover
> Add patroni api client

- glide.lock
- glide.yaml
> Bump client go version

- SECURITY.md
As part of our Rules of Play the Security.md is mandatory, so I just wanted to add it :)
> docs(general): Adding Security.md

- pkg/cluster/k8sres.go
- pkg/cluster/resources.go
Currently when we load spilo cluster resources, we rely on label selectors, instead of the name. That approach might lead to a situation when we have a resource with a proper name, but without proper labels to match label selector. To avoid that we need to fetch resources directly by name, not by label selector
> Fetch cluster resources by name, not by label selectors

- pkg/apiserver/apiserver.go
- pkg/cluster/cluster.go
- pkg/cluster/k8sres.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
- pkg/cluster/types.go
- pkg/cluster/util.go
We will need roles in the controller package
> Make role public

- pkg/cluster/k8sres.go
Use DCS_ENABLE_KUBERNETES_API=true environment to enable kubernetes native deployment
> Set DCS_ENABLE_KUBERNETES_API on empty etcd host var

- Makefile
> Fix staticcheck tool

- manifests/configmap.yaml
- pkg/cluster/util.go
- pkg/util/config/config.go
- pkg/util/constants/roles.go
make operator more configurable
> Set secret name template via config map

- Makefile
- manifests/configmap.yaml
- pkg/apiserver/apiserver.go
- pkg/cluster/k8sres.go
- pkg/controller/controller.go
- pkg/controller/postgresql.go
- pkg/controller/status.go
- pkg/controller/util.go
- pkg/spec/types.go
- pkg/util/config/config.go
- pkg/util/ringlog/ringlog.go
- pkg/util/util.go
introduce ``/clusters/<team>/<cluster>/history/`` endpoint to see last ``[cluster_history_entries]`` diff entries of the cluster spec changes
> Cluster history API endpoint

- pkg/apiserver/apiserver.go
- pkg/cluster/pg.go
Cluster name might contain minus character
> Fix regexp for api endpoint urls

- README.md
Document operator API endpoints.
> Describe available endpoints.

- .travis.yml
- Makefile
- delivery.yaml
> Bump go version to 1.9

- pkg/cluster/pod.go
- pkg/cluster/util.go
- pkg/util/constants/postgresql.go
remove Pod postgresql role constants
> Remove redundant constants

- pkg/cluster/pg.go
Avoid calling ping from the closed connection.
> Retry opening DB connections.

- pkg/cluster/k8sres.go
Add missing master matchLabel for the PDB
> Add missing master matchLabel for the PDB

- pkg/cluster/cluster.go
- pkg/cluster/sync.go
Fix null pointer exception while comparing Pod Disruption Budgets
> Fix Pod Disruption Budget exception 

- manifests/configmap.yaml
> Enable k8s leader election

- pkg/cluster/k8sres.go
Fix pod disruption budget labels
> Fix pod disruption budget labels

- pkg/cluster/cluster.go
- pkg/cluster/pg.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
> Create new databases and change owners of existing ones during sync.

- README.md
Upon the complaint from @hjacobs
> Stackeblockenize the first section of the readme

- pkg/cluster/cluster.go
- pkg/cluster/k8sres.go
- pkg/cluster/sync.go
- pkg/util/config/config.go
> Fix a failure to create new statefulset at sync time.

- pkg/cluster/k8sres.go
- pkg/spec/postgresql.go
Add dockerImage cluster configuration parameter that overrides global
operator defaults when set to a non-empty value.
> Allow per-cluster setting of a docker image.

- pkg/cluster/pg.go
- pkg/util/config/config.go
- pkg/util/users/users.go
- fix the lack of closing the cursor for the query that returned no
rows.
- fix syncing of the user options, as previously those were not
fetched from the database.
> Fix the connection leak and user options sync.

- pkg/cluster/k8sres.go
> Make pod's single container name static

- manifests/infrastructure-roles.yaml
- pkg/controller/util.go
> Warn on infrastructure-roles.yaml format violations

- README.md
> Mention the talk by Josh Berkus and the blog post by Jan Mußler.

- manifests/complete-postgres-manifest.yaml
> Fix loadBalancerConfig

- manifests/complete-postgres-manifest.yaml
> Add an example for cloning a backup from existing cluster

- pkg/cluster/cluster.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
Per report and analysis by Manuel Gomez.
> Make sure the statefulset that is deleted manually gets re-created.

- pkg/controller/controller.go
> Overwrite scalyr api key if the relevant env var is present in the operator pod

- README.md
For #214 
So far only delve setup is described in details, but I think it can be convenient.
> Add a section about debugger

- cmd/main.go
- manifests/configmap.yaml
- manifests/postgres-operator.yaml
- pkg/cluster/resources.go
- pkg/controller/controller.go
- pkg/controller/node.go
- pkg/controller/pod.go
- pkg/controller/postgresql.go
- pkg/controller/status.go
- pkg/util/config/config.go
> Make env var overwrite configmap setting for watching namespaces 

- pkg/util/retryutil/retry_util.go
- pkg/util/retryutil/retry_util_test.go
One can argue about how necessary they are,
but at least I remembered how to do golang.
> Tests for retry_utils

- README.md
Also adds a FOSDEM 2018 talk on the operator
Closes #228
> Create separate Talks section in the README

- README.md
For #226 
Documents how to run all the unit tests for different golang versions and how to debug them.
> Add section about unit tests

- delivery.yaml
This necessary step was missing. Also I update a delivery.yaml version and split image build & push steps.
> Add a new step to run unit tests

- README.md
- cmd/main.go
- pkg/controller/controller.go
- pkg/spec/types.go
- pkg/spec/types_test.go
- pkg/util/k8sutil/k8sutil.go
> Operator should default to the watched namespace

- cmd/main.go
> Remove the second namespace prefix from the operator configmap name

- pkg/controller/controller.go
> Make operator watch its own namespace instead of controller's one

- .travis.yml
An experiment to get rid of annoying problems with travis ci timeouts
> WIP: Use travis_wait to prevent timeout

- README.md
> Document behavior in the case of unaccessible namespaces

- pkg/controller/postgresql.go
Sometimes the operator does not pick up clusters right away when
they are created. The change attempts to shed light on the
reason behind that.
> Make errors in the cluster list function visible.

- pkg/cluster/cluster.go
As part of random improvements idea: move out some part of `compareStatefulSetWith` with cyclomatic complexity 23 to a separate function to simplify it.
> Move container comparison logic to a separate function

- pkg/cluster/k8sres.go
- pkg/cluster/pod.go
- pkg/cluster/util.go
- pkg/cluster/volumes.go
> Add 'team' label to pods, stateful sets, secrets and pod disruption budgets

- pkg/cluster/k8sres.go
> Set WAL_BUCKET_SCOPE_PREFIX to the empty string

- README.md
Frame the scope of the project in the readme to make it clearer on what we want to achieve and focus on.
> Add scope section to readme.

- pkg/cluster/k8sres.go
- pkg/util/config/config.go
Operator side of [this Spilo PR](https://github.com/zalando/spilo/pull/225/files)
> Set up an S3 bucket for the postgres logs

- pkg/cluster/sync.go
Avoid the condition of waiting for the pod that cannot start
PostgreSQL because it ran out of disk space.
> Sync persistent volumes before statefulsets.

- pkg/cluster/sync.go
- pkg/cluster/volumes.go
Do not use statefulset number of pods to figure out running ones
for volume resizing, since the statefulset pointer could be nil.
Instead, look at the actual running pods.
> Fix crash during sync.

- pkg/util/config/config.go
Removes outdated config; see [discussion](https://github.com/zalando-incubator/postgres-operator/pull/301#discussion_r190570585)
> Fix etcd_host default

- pkg/controller/postgresql.go
OB1 bug in the condition deciding whether to sync.
> Avoid possible skipping SYNC events.

- docs/user.md
- manifests/complete-postgres-manifest.yaml
Since this feature is quite important it makes sense to mention it in the user part.
> Add an example of clone feature

- docs/user.md
Another important feature to document
> Add section about volume increase

- docs/cluster_manifest.md
> Document cluster manifests.

- docs/reference/cluster_manifest.md
> Minor formatting fix

- docs/reference/operator_parameters.md
- manifests/configmap.yaml
- pkg/cluster/sync.go
- pkg/util/config/config.go
- pkg/util/constants/aws.go
- pkg/util/volumes/ebs.go
> Make AWS region configurable in the operator config map

- docs/administrator.md
- docs/reference/operator_parameters.md
- manifests/operator-service-account-rbac.yaml
- pkg/cluster/cluster.go
- pkg/controller/controller.go
- pkg/controller/operator_config.go
- pkg/controller/postgresql.go
- pkg/util/config/config.go
- pkg/util/config/crd_config.go
- pkg/util/k8sutil/k8sutil.go
Move submitting service account to a controller; this should not block a controller itself since this code runs in a separate go-routine.
> [WIP] Submit service account during initial Event processing

- pkg/cluster/volumes.go
Do not show 'persistent volumes are not compatible' error for the
volumes that failed to be resized because of the other reasons (i.e.
the new size is smaller than the existing one).
> Avoid showing an extra error when resizing volume fails

- pkg/apiserver/apiserver.go
- pkg/cluster/cluster.go
- pkg/cluster/k8sres.go
- pkg/cluster/pg.go
- pkg/cluster/pod.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
- pkg/cluster/util.go
- pkg/controller/controller.go
- pkg/controller/postgresql_test.go
- pkg/controller/util.go
- pkg/spec/postgresql.go
- pkg/spec/types.go
- pkg/util/config/crd_config.go
- pkg/util/patroni/patroni.go
Among other things, fix a few issues with deepcopy implementation.
> Refactoring inspired by gometalinter.

- README.md
Add godoc link to readme, for whoever whats to peek inside
> Add GoDoc badge to readme

- docs/developer.md
Briefly documents recently added code generation capability
> Document code generation

- pkg/apis/acid.zalan.do/v1/util.go
- pkg/apis/acid.zalan.do/v1/util_test.go
Improve error reporting for short cluster names
> Improve error reporting for short cluster names

- docs/administrator.md
- docs/reference/operator_parameters.md
- pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
- pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cluster/util.go
- pkg/controller/operator_config.go
- pkg/spec/types.go
- pkg/util/config/config.go
Initial version, do not merge.
> [WIP] Grant 'superuser' to the members of  Postgres admin teams

- docs/user.md
Addresses modifications from #396
> From pr #396

- Makefile
- docs/reference/cluster_manifest.md
- manifests/complete-postgres-manifest.yaml
- pkg/apis/acid.zalan.do/v1/postgresql_type.go
- pkg/apis/acid.zalan.do/v1/util_test.go
- pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
- pkg/cluster/k8sres.go
Adds the support for the [upcoming Patroni feature](https://github.com/zalando/patroni/pull/819)
> [WIP] Add the ability to configure replications slots in Patroni

- docs/reference/cluster_manifest.md
- manifests/complete-postgres-manifest.yaml
- pkg/apis/acid.zalan.do/v1/postgresql_type.go
- pkg/apis/acid.zalan.do/v1/util_test.go
- pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
- pkg/cluster/k8sres.go
Patroni [recognizes only 3 names](https://github.com/zalando/patroni/blob/2efd97baabb52076e91eb9f1e76b9dc93c769b4f/patroni/dcs/__init__.py#L308) for the `slots` field
> Rename 'permanent_slots' field to 'slots'

- manifests/operator-service-account-rbac.yaml
- manifests/postgres-operator.yaml
Add missing permissions and settings to get OperatorConfiguration to work, fixes #404
> Make OperatorConfiguration work

- README.md
Since we've connected it, it makes sense also to display the results.
> Add golangci badge

- pkg/cluster/k8sres.go
Pass `cluster_name_label` configuration on to Spilo containers as environment variable `KUBERNETES_SCOPE_LABEL`.
Partial fix for #436.
> Pass cluster_name_label on to Spilo containers

- docs/user.md
Found the section on `roles` a bit hard to read, so I introduced more headers and removed some redundant sentences. (btw, there is no paragraph for `team API roles`)
> Edited Roles section in User documentation

- docs/administrator.md
Fixing links and small errors
Some homogenization of naming things
Added line breaks in some paragraphs
> Minor changes to Admin doc

- pkg/cluster/resources.go
Fix for https://github.com/zalando-incubator/postgres-operator/issues/446
> Don't panic if Service for the role was not found

- docs/index.md
Add link to the recorded talk video.
https://twitter.com/PostgreSQL/status/1087681292416630785
> Add link to video of Oleksii's talk

- pkg/apis/acid.zalan.do/register.go
- pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
- pkg/apis/acid.zalan.do/v1/register.go
- pkg/cluster/k8sres_test.go
- pkg/controller/operator_config.go
- pkg/util/config/config.go
- pkg/util/util.go
fixes #415 
The gofmt is now 100% 
The golint is now 100%
which can be previewed at:
https://goreportcard.com/report/github.com/VineethReddy02/postgres-operator
> gofmt and golint fixes

- Makefile
- pkg/cluster/cluster.go
> fix: update init_containers

- charts/postgres-operator/values.yaml
- docs/reference/operator_parameters.md
- manifests/configmap.yaml
- manifests/postgresql-operator-default-configuration.yaml
- pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
- pkg/cluster/k8sres.go
- pkg/controller/operator_config.go
- pkg/util/config/config.go
Runs non-privileged by default.
Fixes #395 
Happy to make any changes if the team prefers a different approach.
> Config option to allow Spilo container to run non-privileged.

- docs/user.md
using a `kubectl port-forward` example
fix #14
> update db connection part in user docs

- charts/postgres-operator/templates/clusterrole.yaml
- manifests/operator-service-account-rbac.yaml
> add update for CRD to RBAC

- pkg/cluster/k8sres.go
- pkg/cluster/k8sres_test.go
> generate spilo config can return error (with test)

- docs/reference/cluster_manifest.md
- docs/user.md
- manifests/complete-postgres-manifest.yaml
> Improve cluster sidecar documentation

- pkg/cluster/cluster.go
- pkg/cluster/k8sres.go
- pkg/cluster/resources.go
> Some typos/spelling mistakes fix

- manifests/complete-postgres-manifest.yaml
> docs: add storageclass to complete-postgres-manifest example

- CODEOWNERS
> Add Rafia to code owners

- manifests/postgres-operator.yaml
update postgres-operator deployment to apps/v1
Fixes #565 .
> update postgres-operator deployment to apps/v1

- docs/index.md
Add Alexander's talk (https://kccna18.sched.com/event/GrU0).
> KubeCon NA 2018 talk

- docs/reference/operator_parameters.md
> Fix spelling error

- charts/postgres-operator/templates/_helpers.tpl
- charts/postgres-operator/templates/clusterrole.yaml
- charts/postgres-operator/templates/clusterrolebinding.yaml
- charts/postgres-operator/templates/configmap.yaml
- charts/postgres-operator/templates/deployment.yaml
- charts/postgres-operator/templates/serviceaccount.yaml
- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
> Simplify service account name in helm chart

- docs/administrator.md
- docs/developer.md
- docs/gsoc-2019/ideas.md
- docs/index.md
- docs/operator-ui.md
- docs/quickstart.md
- docs/reference/cluster_manifest.md
- docs/reference/command_line_and_environment.md
- docs/reference/operator_parameters.md
- docs/user.md
- manifests/postgres-operator.yaml
- mkdocs.yml
I introduced # H1 headers in each document, but turns out mkdocs doesn't like it.
Can be solved by using html `<h1>` tags.
> Fix mkdocs.yaml and title display in ReadTheDocs sidebar

- README.md
to give a quick overview what the operator is capable of
> added feature list to README

- pkg/cluster/cluster.go
- pkg/cluster/k8sres.go
- pkg/cluster/pod.go
- pkg/cluster/resources.go
- pkg/cluster/types.go
- pkg/cluster/util.go
- pkg/util/k8sutil/k8sutil.go
- ui/operator_ui/spiloutils.py
ToDo: Check backwards compatibility
fixes #674
> [WIP] move StatefulSet to apps/v1

- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
- docs/administrator.md
- manifests/complete-postgres-manifest.yaml
- manifests/configmap.yaml
- manifests/postgresql-operator-default-configuration.yaml
As discussed with @FxKu on slack Oct 4 :)
> document configmap variant of inherited_labels

- docker/logical-backup/dump.sh
instead of using hard-coded key
Fixes #641 
Closes #642
> Logical Backup: fetch cluster_name_label from configuration

- docs/quickstart.md
Fix values-crd.yaml incorrect link
> [Docs] Correct link to values-crd.yaml

- docs/administrator.md
List requires a proceeding empty line
> Fix bad formatting in docs

- pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
> Fix operator_configuration_type.go

- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
- manifests/complete-postgres-manifest.yaml
- manifests/configmap.yaml
load balancers services should not be the default in our examples
> disable load balancers by default in examples

- manifests/operator-service-account-rbac.yaml
Fixes #720 
Thanks @alejom99 for finding this out!
> add get for deployments to operator RBAC

- docs/administrator.md
- docs/developer.md
- docs/index.md
- docs/quickstart.md
- docs/reference/cluster_manifest.md
- docs/reference/operator_parameters.md
- docs/user.md
- manifests/complete-postgres-manifest.yaml
- manifests/minimal-postgres-manifest.yaml
- manifests/standby-manifest.yaml
- pkg/apis/acid.zalan.do/v1/util_test.go
- pkg/util/teams/teams_test.go
To close some issues about undocumented features / settings:
closes #740 
closes #709 
closes #643
closes #617
> extend docs and polish manifest examples

- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
- manifests/postgres-operator.yaml
use tag from CDP retriggered for last commit before v1.3.0 release
> use v1.3.0-dirty tag

- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
- manifests/postgres-operator.yaml
> bump to v1.3.1

- charts/postgres-operator-ui/.helmignore
- charts/postgres-operator-ui/Chart.yaml
- charts/postgres-operator-ui/templates/NOTES.txt
- charts/postgres-operator-ui/templates/_helpers.tpl
- charts/postgres-operator-ui/templates/deployment.yaml
- charts/postgres-operator-ui/templates/ingress.yaml
- charts/postgres-operator-ui/templates/service.yaml
- charts/postgres-operator-ui/templates/serviceaccount.yaml
- charts/postgres-operator-ui/values.yaml
for an own project I created a separate UI helm chart. Related to #722 it could be also helpful for others
#794 provides operator API service, that is needed by the UI
> add first version of ui helm chart

- charts/postgres-operator/crds/postgresqls.yaml
- manifests/postgresql.crd.yaml
- pkg/apis/acid.zalan.do/v1/crds.go
> fix validation for S3ForcePathStyle

- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
- docs/reference/operator_parameters.md
> Fix typo in values file

- pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
- pkg/controller/operator_config.go
In case of missing ClusterDomain in CRD provide a default value. Related to #851
> ClusterDomain default

- docs/reference/cluster_manifest.md
- docs/reference/operator_parameters.md
- docs/user.md
- e2e/tests/test_e2e.py
- manifests/complete-postgres-manifest.yaml
- manifests/minimal-postgres-manifest.yaml
- manifests/standby-manifest.yaml
- ui/manifests/deployment.yaml
update manifests to version 12
+ update docs
+ update UI image in deployment yaml
+ increase `RETRY_TIMEOUT_SEC` in e2e tests
> fix minor issues in docs and manifests

- pkg/cluster/k8sres.go
> pass cluster labels as JSON to Spilo

- docs/reference/cluster_manifest.md
- docs/reference/operator_parameters.md
- docs/user.md
- manifests/configmap.yaml
- manifests/postgresql-operator-default-configuration.yaml
use fresh pgBouncer image: registry.opensource.zalan.do/acid/pgbouncer:master-6
fixes #892
> update image and docs for connection pooler

- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
- docs/reference/cluster_manifest.md
- docs/user.md
- manifests/complete-postgres-manifest.yaml
fix config map values in values.yaml
documentation fixes
> Fix val docs

- ui/Dockerfile
- ui/Makefile
- ui/app/src/edit.tag.pug
- ui/app/src/new.tag.pug
- ui/app/src/postgresql.tag.pug
- ui/manifests/deployment.yaml
- ui/manifests/ui-service-account-rbac.yaml
- ui/operator_ui/main.py
- ui/operator_ui/spiloutils.py
- ui/requirements.txt
- ui/start_server.sh
+ update Dockerfile using new start_server script
+ refactored label filtering
+ setting visibility of resource section via environment variable
Kudos to the actual author of this PR @Jan-M
> [UI] add toggle for connection pooler

- pkg/util/retryutil/retry_util.go
> Fix typo in retry_util

- pkg/cluster/pod.go
> Fix typo in error message

- pkg/cluster/cluster.go
- pkg/cluster/resources.go
> Fix pooler delete

- docs/reference/operator_parameters.md
- pkg/cluster/cluster.go
- needsRollUpdate must not be set to false
> do not block rolling updates with lazy spilo update enabled

- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
- manifests/configmap.yaml
- manifests/postgresql-operator-default-configuration.yaml
> bump pgBouncer image

- .travis.yml
> goveralls ignores coverage from some tests, this PR increases the coverage.

- pkg/cluster/cluster.go
- pkg/cluster/resources.go
> delete secrets the right way

- docs/quickstart.md
> UI Service port forwarding internal port is updated to 80 from 8081.

- .gitignore
Added build and node directory to gitignore file.
> Added build and node directory to gitignore file.

- ui/manifests/kustomization.yaml
> Add kustomize support to Postgres UI. (#1087)

- .github/ISSUE_TEMPLATE/postgres-operator-issue-template.md
> Update issue templates

- charts/postgres-operator/templates/deployment.yaml
- charts/postgres-operator/values.yaml
- cmd/main.go
- docs/reference/command_line_and_environment.md
- pkg/controller/controller.go
- pkg/spec/types.go
> Introduce ENABLE_JSON_LOGGING env variable

- ui/operator_ui/main.py
- ui/operator_ui/spiloutils.py
Closes #1028. As described in issue, it implements support for environment variable `AWS_ENDPOINT`
> Add support in UI for custom S3 endpoints for backups

- pkg/cluster/database.go
- pkg/controller/postgresql.go
Make failure in retry a warning not an error.
> Make failure in retry a warning not an error.

- e2e/scripts/watch_objects.sh
All namespaces and deployments.
> More output from test watch script. 

- pkg/cluster/cluster.go
- pkg/cluster/connection_pooler.go
- pkg/cluster/connection_pooler_new_test.go
- pkg/cluster/connection_pooler_test.go
- pkg/cluster/sync.go
- pkg/controller/postgresql.go
More debug output for trouble shooting of missing sync.
> More debug output for trouble shooting of missing sync.

- charts/postgres-operator/crds/operatorconfigurations.yaml
- charts/postgres-operator/crds/postgresqls.yaml
- manifests/operatorconfiguration.crd.yaml
- manifests/postgresql.crd.yaml
> fix identation in operatorconfiguration CRD and jsonPath case

- .github/workflows/run_e2e.yaml
- .github/workflows/run_tests.yaml
- README.md
compile coverage report and add badges.
> compile coverage report and add badges.

- pkg/apis/acid.zalan.do/v1/crds.go
This patch fixes the bug I reported before #1206
> replace AdditionalProperties with XPreserveUnknownFields FIXES  #1206

- pkg/cluster/volumes_test.go
Error was somehow introduced in last 2 PRs merged.
> Fix function name in test

- charts/postgres-operator/crds/operatorconfigurations.yaml
- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
- manifests/configmap.yaml
- manifests/minimal-fake-pooler-deployment.yaml
- manifests/postgresql-operator-default-configuration.yaml
- pkg/util/constants/pooler.go
fixes #1252 
* and raises pooler image wirth `server_login_retry = 5`
* and set `ConnectionPoolerMinInstances` to 1
> raise pooler image and fix pgversion config in chart

- ui/app/src/postgresql.tag.pug
- ui/app/src/postgresqls.tag.pug
- ui/operator_ui/main.py
- ui/operator_ui/spiloutils.py
* reflect new backup path that got introduced with PG_VERSION env variable
* display cluster status to easier spot a failed setup
* do not print K8s managed fields in manifest
* update cluster costs with min number of pods
> [UI] reflect new backup paths and cluster status

- delivery.yaml
> add logical-backup build and push to delivery.yaml

- ui/operator_ui/spiloutils.py
`s/COMMONG_POOLER_LABEL/COMMON_POOLER_LABEL/g`
> fix typo in pooler env variable

- e2e/README.md
- e2e/tests/test_e2e.py
- pkg/cluster/connection_pooler.go
- pkg/cluster/connection_pooler_test.go
- pkg/cluster/k8sres.go
Do not sync connection pooler when there are no changes in pooler configurations.
> Avoid syncing when possible

- pkg/cluster/cluster.go
> Also sync volumes on updates.

- charts/postgres-operator-ui/values.yaml
> fix small misprint in helm chart

- .zappr.yaml
> Min 2 zalando approvers.

- pkg/cluster/k8sres.go
- pkg/cluster/k8sres_test.go
+ adding one more unit test for 1
> fix when adding only one capability

- pkg/cluster/majorversionupgrade.go
> Log result for major version upgrade.

- docs/developer.md
> Update developer docs to say that GO 1.15 or newer is required.

- charts/postgres-operator/values-crd.yaml
- charts/postgres-operator/values.yaml
Signed-off-by: Pierre Péronnet <pierre.peronnet@ovhcloud.com>
> fix(chart) update comments

- e2e/requirements.txt
- kubectl-pg/cmd/addDb.go
- kubectl-pg/cmd/connect.go
- kubectl-pg/cmd/create.go
- kubectl-pg/cmd/extVolume.go
- kubectl-pg/cmd/scale.go
- kubectl-pg/cmd/update.go
- kubectl-pg/cmd/util.go
- pkg/cluster/cluster.go
- pkg/cluster/connection_pooler.go
- pkg/cluster/k8sres.go
- pkg/cluster/k8sres_test.go
- pkg/cluster/majorversionupgrade.go
- pkg/cluster/sync.go
- pkg/cluster/util.go
- pkg/cluster/volumes.go
- pkg/cluster/volumes_test.go
for main code and kubectl-pg plugin
added mock client for TestTLS unit test
> Fix go lint errors

- README.md
Update readme to reflect major version upgrade.
> Update readme to reflect major version upgrade.

- pkg/cluster/k8sres_test.go
as a follow up to merging #1475
> rework additional volume test

- charts/postgres-operator-ui/templates/deployment.yaml
as suggested here: https://github.com/zalando/postgres-operator/issues/1199#issuecomment-729660273
> using quote in UI deployment template

- pkg/cluster/volumes.go
Do not modify if values are below gp3 minimum throughput.
> Do not modify if values are below gp3 minimum throughput.

- charts/postgres-operator-ui/templates/deployment.yaml
- charts/postgres-operator-ui/templates/ingress.yaml
- charts/postgres-operator-ui/templates/service.yaml
- charts/postgres-operator-ui/templates/serviceaccount.yaml
- charts/postgres-operator/templates/configmap.yaml
- charts/postgres-operator/templates/deployment.yaml
- charts/postgres-operator/templates/operatorconfiguration.yaml
- charts/postgres-operator/templates/postgres-pod-priority-class.yaml
- charts/postgres-operator/templates/service.yaml
- charts/postgres-operator/templates/serviceaccount.yaml
> Add namespace to helm chart resources that need them

- docs/quickstart.md
> document where the chart is hosted

- docs/quickstart.md
> Fix typo in quickstart

- ui/operator_ui/main.py
> fix(ui): uses correct default URL value for WALE_S3_ENDPOINT

- charts/postgres-operator/crds/postgresqls.yaml
- manifests/postgresql.crd.yaml
- pkg/apis/acid.zalan.do/v1/crds.go
Hello. Tolerations subfileds aren't required in all cases. I think that required subfields list should be removed from crd.
> Fixing toleration fields requirements

- pkg/cluster/util.go
add a message when team have an error or not found
> update team message

- README.md
- charts/postgres-operator/crds/operatorconfigurations.yaml
- charts/postgres-operator/values.yaml
- manifests/complete-postgres-manifest.yaml
- manifests/configmap.yaml
- manifests/operatorconfiguration.crd.yaml
- manifests/postgresql-operator-default-configuration.yaml
- pkg/controller/operator_config.go
- pkg/util/config/config.go
Perhaps for next zalando release.
> Bump spilo-14:2.1-p4

- pkg/cluster/cluster_test.go
- pkg/cluster/util.go
- pkg/util/teams/teams.go
- pkg/util/teams/teams_test.go
add a test team member when it's not find
> add test team member

- pkg/cluster/k8sres.go
fixes #1863
introduced by [#1825](https://github.com/zalando/postgres-operator/pull/1825/files#diff-e9c5b05262207b16b959659256e773d9158a1710b89d1b73eca6453888563130R560-R572)
> fix container ports

- pkg/cluster/k8sres.go
- pkg/cluster/k8sres_test.go
fixes #1886 - a breaking change introduced with v1.8.0
> ignore case when checking for envVar existence but do not change it

- pkg/controller/postgresql.go
> Fix typo for receiving add event

- ui/app/src/postgresqls.tag.pug
- ui/manifests/deployment.yaml
- ui/operator_ui/main.py
- ui/operator_ui/static/styles.css
* add new columns for IOPS and throughput
* add tooltips for cost information
* change the cost/month function
* merge default and defined config
> update column and cost function

- charts/postgres-operator/crds/operatorconfigurations.yaml
- charts/postgres-operator/values.yaml
- docs/reference/operator_parameters.md
- e2e/tests/test_e2e.py
- manifests/configmap.yaml
- manifests/operatorconfiguration.crd.yaml
- manifests/postgresql-operator-default-configuration.yaml
- pkg/apis/acid.zalan.do/v1/crds.go
- pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
- pkg/apis/acid.zalan.do/v1/postgresql_type.go
- pkg/cluster/k8sres.go
- pkg/cluster/k8sres_test.go
- pkg/controller/operator_config.go
- pkg/util/config/config.go
- pkg/util/util.go
Configure max requests for CPU and Memory.
> Set maximum CPU and Memory requests on K8s

- pkg/cluster/pod.go
- pkg/cluster/sync.go
another fix after #2009 was merged
> rework map selection in updateSecret

- pkg/cluster/majorversionupgrade.go
Fix major version upgrade return code
> Fix major version upgrade return code

- e2e/tests/k8s_api.py
- pkg/cluster/k8sres.go
- pkg/cluster/resources.go
- pkg/cluster/sync.go
- pkg/util/k8sutil/k8sutil.go
Closes #2017. Previous PR #2019 :)
Image to try: `ghcr.io/tamcore/postgres-operator:v1.8.2-20-g2a3713a5`
> switch to batch API v1 for Jobs

- CODEOWNERS
- MAINTAINERS
adding Polina to CODEOWNERS and MAINTAINERS
> hello hughcapet

- pkg/cluster/majorversionupgrade.go
There is a regression caused by https://github.com/zalando/postgres-operator/pull/2056: upgrade run using postgres user was always failing because of an invalid option.  `-o pipefail` was moved directly to upgradeCommand to fix this.
\+ minor formatting corrections added
> Fix upgrade command

- pkg/cluster/streams.go
When `streams` feature is used, we were seeing error messages about [non-existing publication](https://www.postgresql.org/message-id/CADK3HH%2B9uPg%3DanB-thAMojVhsZk3tYWMwux4YmHB2%2BByJXcE3w%40mail.gmail.com), although the operator created them. Turns out, the operator created the logical replication slots first and was syncing publications after it waited for Patroni to add the slots. Before we merged #2034 we could have been lucky that slots were added later. But with the current code we will always run into this issue which can only be fixed by dropping the slot manually in the DB.
Publications have to be created first. There's also a nice [blog post](https://elephanttamer.net/?p=50) on this topic.
> create publication before creating logical replication slot

- ui/app/src/edit.tag.pug
- ui/app/src/new.tag.pug
- ui/app/src/postgresql.tag.pug
- ui/app/src/postgresqls.tag.pug
- ui/operator_ui/main.py
Update the monthly cost calculation by including the load balancer cost. It costs 0.03 per hour per load balancer. 
Price source: https://aws.amazon.com/elasticloadbalancing/pricing/
Based on issue #1829
> [UI] include load balancer in the monthly cost calculation

- README.md
- charts/postgres-operator/crds/operatorconfigurations.yaml
- charts/postgres-operator/values.yaml
- manifests/complete-postgres-manifest.yaml
- manifests/configmap.yaml
- manifests/operatorconfiguration.crd.yaml
- manifests/postgresql-operator-default-configuration.yaml
- pkg/controller/operator_config.go
- pkg/util/config/config.go
Bumped Spilo 14 image tag from 2.1-p6 to 2.1-p7.
This PR resolves #2078.
> Bumped Spilo 14 image tag to 2.1-p7

- charts/postgres-operator/values.yaml
> Fixed tiny typo in values.yaml

- pkg/cluster/resources.go
#2110 was merged into the wrong branch
@godzilla-s fyi
> delete secret resource from map

- pkg/cluster/pod.go
#1984 introduced a bug when fetching the master candidate pod the name is not set for single node clusters. Results in the following error:
```
could not get master candidate pod: resource name may not be empty
```
The pod needs only to be fetched when there's a replica that can become the master. If there's only the master then we already fetched the pod above.
> fix migration of single-node clusters

- charts/postgres-operator/templates/operatorconfiguration.yaml
This part was provided by alexey-gavrilov-flant in #1986 and is missing by accident in #2115.
It is needed to fix #2114, also.
> allow templating in .Values.configGeneral also

- pkg/cluster/cluster.go
- pkg/cluster/sync.go
fix regression introduced by #2187
> set wal_level config not on empty parameters map

- ui/app/src/postgresql.tag.pug
Show pooler DNS when success creating pooler.
> Show pooler DNS when success creating pooler

- pkg/cluster/connection_pooler.go
wrong default assignment created in #2146 and raised [here](https://github.com/zalando/postgres-operator/issues/2201#issuecomment-1413798114)
> minor fix to pooler TLS support

- .github/workflows/run_e2e.yaml
- .github/workflows/run_tests.yaml
Update go-version in github workflows
> Switch gh workflows to go 1.18.9

- run_operator_locally.sh
Hello! Thank you for this lovely project. We've been using `run_operator_locally.sh` in CI and also on local developer machines and noticed that rarely the setup fails when waiting for the port-forward to succeed.
In that case, the symptom is:
```
...
Wait for port forwarding to take effect
Wait for port forwarding to take effect
Wait for port forwarding to take effect
Wait for port forwarding to take effect
Wait for port forwarding to take effect
Wait for port forwarding to take effect
The command curl --location --silent --output /dev/null http://127.0.0.1:8080/clusters timed out
```
`run_operator_locally.sh` currently does _not_ attempt to inspect the success of the `kubectl port-forward` process after sending it to the background.
If the port-forward setup fails, the subsequent …
> run_operator_locally.sh: more retrying, debuggability

- Makefile
- docker/build_operator.sh
- e2e/Dockerfile
- e2e/Makefile
Remove the old metadata convention file to among other things fix GHCR build pipeline
> Remove scm-source.json creation

- Makefile
> bump go to 1.19.8 everywhere

- charts/postgres-operator/values.yaml
> [#2119] fix imagePullSecrets indentation

- pkg/util/k8sutil/k8sutil.go
> check pg version

- pkg/cluster/volumes.go
> log error why ebs volume modifying fails

- pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
Generate deepcopy to show new PVC data type `PersistentVolumeClaimRetentionPolicy`
> Generate deepcopy to show new PVC data type

- charts/postgres-operator/crds/postgresqls.yaml
- manifests/postgresql.crd.yaml
- pkg/apis/acid.zalan.do/v1/crds.go
> Reflect new stream fields in CRD

- docker/Dockerfile
User Alpine 3 to stay up to date
closes #2479
> Use Alpine 3 to stay up to date

- pkg/cluster/cluster.go
- pkg/cluster/sync.go
Small bug that got introduced with #2472
> fix when syncing standby discription

- ui/app/src/new.tag.pug
> Fixed Throughput typo

- charts/postgres-operator/templates/deployment.yaml
- charts/postgres-operator/values.yaml
Fixes https://github.com/zalando/postgres-operator/issues/2672
Inspired from same feature from UI chart.
> feat: Add extraEnvs to operator helm chart

- pkg/util/users/users.go
> quote admin user to allow names with special characters

- pkg/cluster/majorversionupgrade.go
* adding option with "primary" for major upgrade
> Integrate spilo with Patroni 4

- docs/administrator.md
- docs/user.md
- pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
codegen was forgotten to run in #2449
this PR also adds examples how to use command in sidecars
> add sidecar command examples and update codegen

- pkg/cluster/k8sres.go
Set the value from the critical-operation-pdb's selector if PDBs are enabled
https://github.com/patroni/patroni/pull/3257
https://github.com/zalando/spilo/pull/1093
> Configure (upcoming) Patroni bootstrap labels feature

- pkg/cluster/k8sres.go
follow up for https://github.com/zalando/postgres-operator/pull/2872
> Fix wrong condition for bootstrap labels
