zalando/postgres-operator

cmd/main.go, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/pg.go, pkg/cluster/sync.go, pkg/controller/controller.go, pkg/controller/exec.go, pkg/util/config/config.go, pkg/util/teams/teams.go
Command-line options --nodatabaseaccess and --noteamsapi disable all
teams api interaction and access to the Postgres database. This is
useful for debugging purposes when the operator runs out of cluster
(with --outofcluster flag).
The same effect can be achieved by setting enable_db_access and/or
enable_teams_api to false.
=> Allow disabling access to the DB and the Teams API.

.gitignore, README.md
* fix typo in README
* add generated `scm-source.json` to `.gitignore`
=> Fix typo & .gitignore

Makefile, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/util/constants/constants.go
Updates to statefulset spec for fields other than 'replicas' and
containers' are forbidden. However, it is possible to delete the old
statefulset without deleting its pods and create the new one, using the
changed specs. The new statefulset shall pick up the orphaned pods.
Change the statefulset's comparison to return the combined effect of
all checks, not just the first non-matching field.
The environment variables in the statefulset are now sorted based on the name.
As a result, a one-time upgrade of all clusters might be necessary.
=> Replace the statefulset if it cannot be updated.

pkg/cluster/cluster.go, pkg/cluster/pg.go, pkg/cluster/sync.go, pkg/controller/postgresql.go
In order to make code more homogenous it would make sense to return error in methods like SyncCluster and Delete instead of just logging it
=> Return error instead of logging it

pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/pg.go, pkg/cluster/pod.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/controller/controller.go, pkg/controller/exec.go, pkg/controller/pod.go, pkg/controller/postgresql.go, pkg/controller/util.go, pkg/spec/postgresql.go, pkg/util/retryutil/retry_util.go, pkg/util/teams/teams.go, pkg/util/users/users.go
Use lowercase for kubernetes objects
Use %v instead of %s for errors
Start error messages with a lowercase letter.
=> Fix error messages

pkg/controller/postgresql.go
Fix the previous implementation of the same idea.
=> Run sync cluster when previous add or update failed.

pkg/controller/postgresql.go
if cluster got repaired during the update or sync we need to reset Error field of the cluster object
=> Reset cluster error on successful update or sync

pkg/util/util.go
Use correct md5 length while checking password of the user
=> Fix password check in pguserpassword function

manifests/testpostgresql.yaml, pkg/spec/postgresql.go
Change maintenance window format to more readable form:
``{weekday}:{start time %H:%M}-{end time %H:%M}``
- minor improvements
=> Change maintenance window format

pkg/cluster/cluster.go
Check for ZalandoDNSNameAnnotation ("external-dns.alpha.kubernetes.io/hostname") while comparing services.
=> Check for dns annotation of the service

pkg/cluster/resources.go, pkg/cluster/util.go, pkg/util/constants/annotations.go
In case the whole annotation changes (like the external DNS) we
don't want to keep the old one hanging around. Unline specs, we
don't expect anyone except the operator to change the annotations.
Use StrategicMergePatchType in order to replace the annotations
map completely.
This fixes #45
=> Replace service annotations when updating services.

manifests/configmap.yaml, manifests/testpostgresql.yaml, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/spec/postgresql.go, pkg/spec/types.go, pkg/util/config/config.go, pkg/util/constants/annotations.go
- make the load balancer configurable on a per cluster and operator-wide level
- restrict connections to clusters with the load balancers but without allowedSourceRanges defined.
Addresses #54
=> Configure load balancer on a per-cluster and operator-wide level

pkg/cluster/pod.go
Avoid error messages like this one:
time="2017-07-12T07:35:37Z" level=info msg="Recreating master pod '/'" cluster-name=team-example pkg=cluster worker=2
time="2017-07-12T07:35:37Z" level=error msg="could not sync cluster 'default/team-example': could not sync statefulsets: could not recreate pods: could not recreate master pod '/': could not delete pod: resource name may not be empty" pkg=controller worker=2
=> Avoid re-creating master pod if it is empty

pkg/util/users/users.go
Check if there are `alter user` sql statements to run before wrapping them with `DO` block
=> Skip running empty set of queries

pkg/controller/controller.go
Instead of setting Level for the `logrus.Entry` we must set it for the `Logger` instead
=> Fix setting debug logger level

pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/pg.go, pkg/cluster/pod.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/cluster/volumes.go, pkg/controller/controller.go, pkg/controller/pod.go, pkg/controller/postgresql.go, pkg/controller/util.go, pkg/spec/types.go, pkg/spec/types_test.go, pkg/util/teams/teams.go, pkg/util/teams/teams_test.go, pkg/util/util_test.go
Instead of mentioning cluster name in the logger message, use logger fields for that;
start all the log messages with a lowercase letters
=> Pass cluster name as a logger field

cmd/main.go, pkg/controller/controller.go, pkg/controller/util_test.go, pkg/spec/types.go
Moving config to the spec package will help us avoiding cyclic dependencies
=> Move controller config to the spec package 

pkg/apiserver/apiserver.go, pkg/cluster/cluster.go, pkg/controller/controller.go, pkg/controller/postgresql.go
If we delete a cluster we can discard all the events preceding to the deletion of the cluster
=> Discard cluster events from the queue on cluster delete

pkg/controller/status.go, pkg/spec/types.go
Display size of the queue for each worker in the ``/status`` api endpoint
=> Worker queue size in the status api endpoint

pkg/controller/postgresql.go
Delete cluster key from the clusters list only when delete procedure is finished.
Clusters map is used to determine cluster to send a Pod event to. If there's no cluster in the clusters map, pod event will be dismissed, which will result in pod deletion stuck.
=> Fix cluster delete

manifests/configmap.yaml, pkg/cluster/k8sres.go, pkg/cluster/util.go, pkg/spec/postgresql.go, pkg/spec/postgresql_test.go, pkg/util/config/config.go
The changes add a new JSON node `clone` with possible values `cluster`
and `timestamp`. `cluster` is mandatory, and setting a non-empty
`timestamp` triggers wal-e point in time recovery. Spilo and Patroni do
the whole heavy-lifting, the operator just defines certain variables and
gathers some data about how to connect to the host to clone or the
target S3 bucket.
=> Allow cloning clusters from the operator.

pkg/cluster/pg.go
that will fix "attempted to close an empty db connection object" warnings
=> Add missing return

pkg/cluster/cluster.go, pkg/cluster/pod.go, pkg/cluster/util.go
While performing rolling upgrade, before terminating master pod, do manual failover to a random replica
=> Perform manual failover on cluster rolling upgrade

pkg/cluster/cluster.go, pkg/cluster/pg.go
=> Adding '_' to allowed chars.

pkg/cluster/pod.go
Do not perform failover for the clusters with no replicas
=> Skip manual failover for 1-pod clusters

README.md
some clusters endpoints had /workers prepended to it by mistake.
=> Fix the endpoints

pkg/cluster/util.go
Previously, a timer had been reset on every message received through
the pod channel.
=> Fix pod wait timeouts.

cmd/main.go, manifests/postgres-operator.yaml
Use clear name for env var denoting namespace to watch
=> Use clear name for env var denoting namespace to watch

pkg/cluster/sync.go, pkg/controller/postgresql.go, pkg/spec/postgresql.go
In case sync of the cluster failed we need to set proper status to the cluster.
The same if sync of the cluster succeeded
=> Set status of the cluster on sync fail/success

pkg/cluster/pg.go
Apparently the retry function's first parameter is the duration of
a single attempt and it cannot be zero.
=>  Fix division by zero when connecting to the DB.

pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/sync.go
- Call comparison function in the case of the sync as well as for update
- Include full cluster name in PDB name
- Assign cluster labels to the PDB object
=> Minor fixes around PDB (pod-distruption-budget) syncing:

README.md
Cluster created via `minimal-postgres-manifest` has the name `acid-minimal-cluster`, not `acid-test-cluster`
=> Change cluster name to "acid-minimal" in readme

README.md, manifests/configmap.yaml, pkg/cluster/k8sres.go, pkg/spec/postgresql.go, pkg/util/config/config.go
Our goal is to provide "dedicated" Kubernetes nodes for Postgres instances and this PR introduces a config option to set a node toleration on the Postgres pods.
The configmap is extended with the option `toleration` which allows configuration of a Kubernetes toleration to match node taints. These nodes are then reserved for Postgres pods and don't get any other pods scheduled except the toleration is added.
If the `toleration` option is not configured, no toleration specs are added to the StatefulSet. If a toleration is defined like:
```
toleration: "key:postgres,operator:Exists,effect:NoSchedule"
```
following specification is added to the StatefulSet:
```
tolerations:
- effect: NoSchedule
key: postgres
operator: Exists
```
=> Add node toleration config to PodSpec

README.md
Add a link to Patroni :tada: 
The README does not really use wording consistently right now (upper/lowercase, PostgreSQL vs Postgres, etc), I guess it deserves some later Stakkenblochen PR.
=> link to Patroni

manifests/configmap.yaml, pkg/cluster/k8sres.go, pkg/cluster/pod.go, pkg/controller/node.go, pkg/util/config/config.go
Previously, the operator started to move the pods off the nodes to be
decomissioned by watching the eol_node_label value. Every new postgres
pod has been created with the anti-affinity to that label, making sure
that the pods being moved won't land on another to be decomissioned
node.
The changes introduce another label that indicates the ready node.  The
new pod affinity will ensure that the pod is only scheduled to the node
marked as ready, discarding the previous anti-affinity.  That way the
nodes can transition from the pending-decomission to the other statuses
(drained, terminating) without having pods suddently scaled to them.
In addition, rename the label that triggers the start of the upgrade
process to node_eol_label (for consistency with node_readiness_label)
and set its default …
=> Tweak our reaction to the cluster upgrade process.

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/util.go, pkg/spec/postgresql.go, pkg/spec/postgresql_test.go, pkg/util/teams/teams.go
For a role defined in both the infrastructure roles secret and the cluster manifest use the infrastructure role definition and add flags defined in the manifest. #166
=> Avoid overwriting infrastructure roles.

README.md, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/util.go, pkg/util/config/config.go
Disallow defining new users either in the cluster manifest, teams
API or infrastructure roles with the names mentioned in the new
protected_role_names parameter (it is a list).
Additionally, forbid defining a user with the name matching either
super_username or replication_username, so that we don't overwrite
system roles required for correct working of the operator itself.
=> Avoid overwriting critical users.

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/pg.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/util/users/users.go
- make sure that the secrets for the system users (superuser, replication)
are not deleted when the main cluster is. Therefore, we can re-create
the cluster, potentially forcing Patroni to restore it from the backup
and enable Patroni to connect, since it will use the old password, not
the newly generated random one.
- when syncing users, always check whether they are already in the DB.
Previously, we did this only for the sync cluster case, but the new
cluster could be actually the one restored from the backup by Patroni,
having all or some of the users already in place.
- delete endponts last. Patroni uses the $clustername endpoint in order
to store the leader related metadata. If we remove it before removing
all pods, one of those pods running Patroni will re-create it and the
next …
=> Fixes for the case of re-creating the cluster after deletion.

README.md, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/util/config/config.go
Use a ConfigMap set by the operator configuration option `pod_environment_configmap` in order to supply arbitrary environment variables to Spilo.
On conflict between the options supplied by the operator and those listed in the pod environment ConfigMap the operator options win.
This is a rebase of https://github.com/zalando-incubator/postgres-operator/pull/152/ to the recent master to eliminate conflicts.
=> custom-env-rebased

README.md, pkg/cluster/k8sres.go, pkg/cluster/sync.go, pkg/util/config/config.go
Reduce the number of instances to the min_instances if it is lower and
to the max_instances if it is higher. -1 for either of those means there
is no lower or upper bound.
In addition, terminate the operator when there is a nonsense in the
configuration (i.e. max_instances < min_instances).
=> Introduce higher and lower bounds for the number of instances

pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/sync.go, pkg/util/config/config.go
When the `scalyr_api_key` key is defined in the configmap, this adds a sidecar container named `scalyr-agent` to PostgreSQL pods that ships all logs to Scalyr.
The sidecar image is configurable with the `scalyr_image` configmap key and defaults to the currently newest CDP build from [the currently-private Spilo Scalyr sidecar repository](https://github.bus.zalan.do/acid/spilo-sidecar-scalyr) in the private image registry.
That image is very simple: it just installs the Scalyr agent and creates a configuration file that consumes the environment variables set by the Operator.  It should be easy to make that repository public if we build the image on top of [the official Scalyr agent image on Docker Hub](https://hub.docker.com/r/scalyr/scalyr-agent/).  This was not done for the private image …
=> Scalyr agent sidecar for log shipping

pkg/cluster/k8sres.go
This will allow the Scalyr image to add a custom attribute to shipped
log entries that notes the name of the originating pod.
=> Add PostgreSQL pod name Scalyr sidecar environment

pkg/cluster/k8sres.go
Another tiny bit of information that could be useful for log filters once we start deploying clusters into separate namespaces.
=> Add PostgreSQL pod namespace Scalyr sidecar environment

pkg/cluster/pod.go, pkg/controller/node.go, pkg/controller/node_test.go, pkg/util/config/config.go
- use the lack of lifecycle-status: ready label to trigger the migration
- make sure the nodes are examined on start of the operator in order to avoid missing a migration of the set of nodes when the operator is killed in the process.
=> Improve behavior on node decomissionining

pkg/cluster/pod.go, pkg/cluster/resources.go, pkg/controller/node.go
Avoid migrating replica pods, since they will be handled by the
node draining anyway (the PDB specifies that only masters are to
be kept).
Allow migration of the single-pod clusters.
=> Migrate only master pods. Migrate single masters.

pkg/cluster/cluster.go
This includes a comparison on container names being equal in the decision of whether a Statefulset has been updated.
=> Consider container names in Statefulset diffs

README.md, manifests/configmap.yaml, manifests/minimal-postgres-manifest.yaml, pkg/cluster/k8sres.go, pkg/util/config/config.go
Previously, it was set to the lifecycle-status:ready, breaking a
lot of minikube deployments. Also it was not possible before to run
with this label set to an empty value.
Document the effect of the label in the new section of the
documentation.
Addresses #203
=> Set node_readiness_label default to an empty value.

Makefile, docker/DebugDockerfile
You can specify an environment variable DEBUG 1/0 to enable/disable
debug mode. Debug mode assumes delve dependency for remote debugging,
and debugging symbols for go build.
=> Add debug mode

docker/DebugDockerfile
There was a typo in DebugDockerfile in delve port.
=> Fix typo in port

pkg/cluster/k8sres.go, pkg/spec/postgresql.go
Populate `WAL_BUCKET_SCOPE_SUFFIX` Spilo environment variable with the cluster manifest UID, which will be used as a suffix for the S3 bucket. The end goal is to allow deleting a cluster and then deploying another one with the same name without the latest one reusing the S3 bucket of the previous one.
=> Use cluster UID as a suffix to the WAL bucket.

pkg/cluster/k8sres.go
This allows using S3 API in order to simplify finding all
folders that are different only by a suffix, since the
suffix delimiter will not occur in the suffix itself.
=> Change the suffix delimiter to slash.

pkg/spec/types.go
=> Avoid reading the namespace file every time the NamespacedName val is decoded.

pkg/cluster/cluster.go, pkg/cluster/pod.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/util/patroni/patroni.go
There used to be a masterLess flag that was supposed to indicate whether the cluster it belongs to runs without the acting master *by design*. At some point, as we didn't really have support for such clusters, the flag has been misused to indicate there is no master in the cluster. However, that was not done consistently (a cluster without all pods running would never be masterless, even when the master is not among the running pods) and it was based on the wrong assumption that the masterless cluster will remain masterless until the next attempt to change that flag, ignoring the possibility of master coming up or some node doing a successful promotion. Therefore, this PR gets rid of that flag completely.
When the cluster is running with 0 instances, there is obviously no master and it …
=> Make code around recreating pods and creating objects in the database less brittle

pkg/apiserver/apiserver.go, pkg/cluster/k8sres.go, pkg/cluster/pg.go, pkg/cluster/resources.go, pkg/cluster/util.go, pkg/util/retryutil/retry_util.go, pkg/util/retryutil/retry_util_test.go, pkg/util/users/users.go
Improvements are mostly style related, like:
* drop else when there is a return statement in the previous if
* comments for retry_utils
* names consistency
=> Some improvements for golint, ineffassign and misspell

pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/util.go
=> Remove Patroni leftover objects on cluster deletion.

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go, pkg/cluster/sync.go, pkg/controller/util.go, pkg/controller/util_test.go, pkg/spec/types.go
When the password in the infrastructure role is updated, re-generate the
secret for that role.
Previously, the password for an infrastructure role was always fetched from
the secret, making any updates to such role a no-op after the corresponding
secret had been generated.
Addresses #149
=> update individual role secrets from infrastructure roles

pkg/cluster/k8sres.go
By default, spilo sets WAL_BUCKET_SCOPE_PREFIX depending on the cluster
namespace, possibly to a non-empty string. However, we won't be able to
clone those clusters, as the clone prefix is always set to an empty string.
We could go the other way around and set both WAL_BUCKET_SCOPE_PREFIX
and CLONE_WAL_BUCKET_SCOPE_PREFIX to a non-default value that depends
on the cluster's namespace, but it seems that we don't need this
feature for now (no conflict will occur even for clusters with the
same name and different namespaces because of the SCOPE_SUFFIX) and
it requires some additional testing first.
=> Fix clone for origins in non-default namespaces.

README.md, manifests/operator-rbac.yaml
Note that the account here is named zalando-postgres-operator and not
the 'operator' default that is created in the serviceaccount.yaml and
also used by the operator configmap to create new postgres clusters.
This is done intentionally, as to avoid breaking those setups that
already work. Ideally, the operator should be run under the
zalando-postgres-operator service account. However, the service account
used to run Postgres clusters does not require all those privileges and
is described at
https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml
The service account defined here acquires some privileges not really
used by the operator (i.e. we only need list and watch on configmaps),
this is also done intentionally to avoid breaking things if someone
decides to configure …
=> Define the operator RBAC

pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/util.go
I was never supposed to be there, but implicitely statefulset creates a selector out of meta.labels field. That is the problem with recent Kubernetes, since statefulset cannot pick up pods with non-matching label selectors, and we rely on statefulset picking up old pods after statefulset replacement.
=> Remove team from statefulset selector

pkg/cluster/util.go
The sync should continue in case  team service issue/unexpected response; return an empty list of team members as a fallback value. The change affects `Create()`, `Sync()` and `Update()`
=> Tolerate issues of the Teams API

README.md, manifests/configmap.yaml, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/sync.go, pkg/controller/controller.go, pkg/controller/util.go, pkg/util/config/config.go
Stateful sets need a service account to create Spilo pods. This PR automates deployment of such an account, thereby reducing manual work required to deploy a database.
=> Deploy service account for pod creation on demand

pkg/cluster/sync.go
Avoid showing "there is no service in the cluster" when syncing a
service for the cluster if the operator has been restarted after
the cluster had been created.
=> Fix a bug with syncing services

README.md, manifests/configmap.yaml, manifests/postgres-operator.yaml
Trying to get down the content needed for first start of operator, default config should be easy to deploy on minikube.
=> README and deployment manifest updates

README.md, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/controller/controller.go, pkg/controller/postgresql.go, pkg/controller/postgresql_test.go, pkg/util/config/config.go
- deprecate useLoadBalancer, replicaLoadBalancer from the manifest
and enable_load_balancer from the operator configuration. Those
options become no-op with this commit.
- Make sure the endpoint being created during the sync receives proper
addresses subset. This is more critical for the replicas, as for the
masters Patroni will normally re-create the endpoint before the
operator.
- Update the README and unit tests.
=> Deprecate old LB options, fix endpoint sync.

.gitignore, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/util/k8sutil/k8sutil.go
Store pending rolling update flag in the cluster's StatefulSet annotation and clear it once the rolling update finished. Doing that allows us to resume an incomplete rolling update even if the instance of the operator that started it is no longer running.
That required to amend the StatefulSet comparison logic to act on StatefulSet annotations.
Also, if there is a failure to update the running StatefulSet with the rolling update flag value, the operator checks the value of the flag as stored inside the Cluster definition and reset the flag in the actual running StatefulSet if the in-memory flag is False. That way, if the actual rolling update succeeds, but the update of the rolling update flag fails, the rolling update won't be repeated.
Fix a few issues with the services:
- when …
=> Annotate StatefulSets with pending rolling update status flag

pkg/cluster/cluster.go, pkg/controller/postgresql.go
When there is an error happening upon deletion of the Kubernetes object
belonging to the cluster being removed, it makes no sense to abort the
deletion: the manifest will be removed anyway, therefore all the objects
after the one we aborted at will stay forever.
=> Avoid terminating delete on errors.

pkg/cluster/pod.go, pkg/cluster/volumes.go
After an unsuccessful initial cluster sync it may happen that the
cluster statefulset is empty. This has been made more likely since
88d6a7be3, since it has introduced syncing volumes before statefulsets,
and the volume sync may fail for different reasons (i.e. the volume has
been shrinked, or too many calls to Amazon).
=> Fix a crash on node migration.

pkg/util/config/config.go
Includes Patroni v1.4.4 that removes an issue with k8s v1.10+ API
=> Bump up default Spilo image

pkg/cluster/cluster.go, pkg/cluster/pod.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/spec/types.go, pkg/util/patroni/patroni.go
Call Patroni API /config in order to set special options that are
ignored when set in the configuration file, such as max_connections.
Per https://github.com/zalando-incubator/postgres-operator/issues/297
=> Use Patroni API to set bootstrap-only options.

pkg/cluster/exec.go, pkg/spec/types.go, pkg/util/constants/kubernetes.go
The original code assumed only one container per pod.
=> Fix exec into pods to resize volumes for multi-container pods.

.travis.yml
- explicitely set sudo to false, since we don't need it and it
slows-down builds.
- use the newest go toolchain.
=> Update travis configuration.

pkg/cluster/k8sres.go
The old way of specifying it with the annotation is deprecated and not
available in recent Kubernetes versions. We will keep it there anyway
until upgrading to the new go-client that is incompatible with those
versions.
Per https://github.com/zalando-incubator/postgres-operator/issues/337
=> Use the StorageClassName field of the volumeClaimTemplate.

pkg/cluster/cluster.go
Otherwise, two corner cases may happen:
- waitForPodLabel writes to the podLabelErr channel that has been
already closed by the outer routine
- the outer routine exists and the caller subscribes to the pod
the inner goroutine has already subscribed to, resulting in panic.
The previous commit https://github.com/zalando-incubator/postgres-operator/commit/fe47f9ebeadd54639913296735158b42d17ee012
that touched that code added the cancellation channel, but didn't bother
to actually wait for the goroutine to be cancelled.
Per report from @valer-cara.
Original issue: https://github.com/zalando-incubator/postgres-operator/issues/342
=> Switchover must wait for the inner goroutine before it returns.

manifests/postgres-operator.yaml
so that those who run quickstart  can test example multi-namespace setup
=> Upgrade version to enable RBAC in multiple namespace

pkg/cluster/k8sres.go
Avoid duplicating POD_NAME and POD_NAMESPACE that already bundled
every sidecar.
Do not complain on the lack of SCLALYR_SERVER_HOST, since it is set to
https://upload.eu.scalyr.com in the container we use.
Do not mentioned SCALYR_SERVER_HOST in the error messages, since it is
derived from the cluster name automatically.
=> Improve generation of Scalyr container environment.

pkg/controller/controller.go
Interpretation of flags -nodatabaseacces and -noteamsapi was broken since 3a9378d3b8edef1789e062e1f446018b9f8e6528
=> Fix disabling database access and teams API via command-line options.

glide.lock, glide.yaml, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/exec.go, pkg/cluster/k8sres.go, pkg/cluster/pod.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/cluster/volumes.go, pkg/controller/controller.go, pkg/controller/node.go, pkg/controller/node_test.go, pkg/controller/pod.go, pkg/controller/postgresql.go, pkg/controller/util.go, pkg/controller/util_test.go, pkg/spec/postgresql.go, pkg/spec/types.go, pkg/util/config/crd_config.go, pkg/util/k8sutil/k8sutil.go, pkg/util/patroni/patroni.go, pkg/util/volumes/ebs.go, pkg/util/volumes/volumes.go
Upgrade go-client to v6, implement deepcopy for CRDs, cope with some minor API changes (and packages moved).
=> Client go upgrade v6

docs/reference/operator_parameters.md
Per a gripe from @angapov: https://github.com/zalando-incubator/postgres-operator/issues/355
=> Fix a link to the CRD manifest.

pkg/apiserver/apiserver.go, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/pg.go, pkg/cluster/pod.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/controller/controller.go, pkg/controller/pod.go, pkg/controller/postgresql.go, pkg/spec/postgresql.go, pkg/util/config/crd_config.go, pkg/util/patroni/patroni.go, pkg/util/teams/teams.go, pkg/util/users/users.go
Linter-induced code refactoring, run round 2.
Run more linters in the gometalinter, i.e. deadcode, megacheck,
nakedret, dup.
More consistent code formatting, remove two dead functions, eliminate
naked a bunch of naked returns, refactor a few functions to avoid code
duplication.
=> linter-induced refactoring, next steps

glide.lock, glide.yaml, pkg/spec/types.go
Not much changes, except for one function that has been deprecated.
However, unless we find a way to use semantic version comparisons like
'^' on a branch name, we would have to update the apimachinery,
apiextensions-apiserver and code-generator dependencies manually.
Also, slash a linter warning about RoleOriginUnknown being not used.
=> Move to client-go 8.

pkg/cluster/util.go
Previously it has been supported by the operator, but the validity check
excluded it for no reason.
=> Include CREATEROLE to the list of allowed flags.

pkg/controller/controller.go, pkg/controller/postgresql.go, pkg/util/config/util.go
Assign the list of clusters in the controller with the up-to-date list
of Postgres manifests on Kubernetes during the startup.
Node migration routines launched asynchronously to the cluster
processing rely on an up-to-date list of clusters in the controller to
detect clusters affected by the migration of the node and lock them
when doing migration of master pods. Without the initial list the
operator was subject to race conditions like the one described at
https://github.com/zalando-incubator/postgres-operator/issues/363
Restructure the code to decouple list cluster function required by the
postgresql informer from the one that emits cluster sync events. No
extra work is introduced, since cluster sync already runs in a separate
goroutine (clusterResync).
Introduce explicit initial cluster …
=> Populate list of clusters in the controller at startup.

pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/resources.go, pkg/cluster/util.go, pkg/spec/postgresql.go, pkg/util/util.go
Previously, the operator put pg_hba into the bootstrap/pg_hba key of
Patroni. That had 2 adverse effects:
- pg_hba.conf was shadowed by Spilo default section in the local
postgresql configuration
- when updating pg_hba in the cluster manifest, the updated lines were
not propagated to DCS, since the key was defined in the boostrap
section of Patroni.
Include some minor refactoring, moving methods to unexported when
possible and commenting out usage of md5, so that gosec won't complain.
Per https://github.com/zalando-incubator/postgres-operator/issues/330
=> Configure pg_hba in the local postgresql configuration of Patroni.

pkg/cluster/cluster.go
When an operator watches all namespaces, it internally [uses the k8s constant `v1.NamespaceAll`](https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/controller/controller.go#L378) to represent all namespaces.  As of k8s API v1, this constant evaluates to the empty string, and passing the empty string as a namespace of a particular namespaced k8s resources fails the REST `Patch` call. The bug prevents creating clusters and shows up in the operator log as a message:
> could not update status: Namespace parameter required
=> Use cluster's own namespace to patch the cluster manifest

glide.lock, glide.yaml, pkg/apiserver/apiserver.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go, pkg/controller/controller.go, pkg/controller/logs_and_api.go, pkg/controller/postgresql.go, pkg/spec/types.go, pkg/util/patroni/patroni.go, pkg/util/teams/teams.go, pkg/util/teams/teams_test.go
Dep enforces this. I have no idea why it just started bothering me about it but it seemed like a safe thing to fix. Reference https://github.com/sirupsen/logrus/blob/master/example_basic_test.go#L4 or the default name capitalization in github to confirm I'm not off the mark?
=> Fix the casing of github.com/Sirupsen/logrus to match what the project itself uses

pkg/apis/acid.zalan.do/v1/util_test.go, pkg/cluster/cluster_test.go, pkg/controller/controller.go, pkg/controller/postgresql.go
I upgraded to 1.11 on my laptop and thought I would clean up some minor things. Newer gofmt, a tweak to a format string to please newer `vet`, and fixing one test where the error message appears to vary between Go versions.
=> Some tweaks to ensure compat with newer Go

docs/administrator.md, pkg/cluster/cluster.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/util.go
1. Fix the bug that prevented logging the reasons for a rolling updates in some of the cases and remove the `todo` related to that
2. Use the word `update` everywhere instead of `upgrade` to be consistent with `k8s` docs.
3. Refer to containers in diffs not only by index in the `[]containers`, but also by name.
4. Briefly document how find reasons for rolling updates.
5. Minor typo/logging improvements.
=> Improve reporting about rolling updates

pkg/apiserver/apiserver.go, pkg/apiserver/apiserver_test.go
Make regexps for API more flexible, to allow e.g. teamId contains dashes. Solves #394
=> API url regexps

.zappr.yaml
Despite no longer being used for PR approvals, it is still needed for CDP web hooks to function correctly.
=> Restore .zappr.yaml

docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, manifests/complete-postgres-manifest.yaml, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/apis/acid.zalan.do/v1/util_test.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/util/config/config.go, pkg/util/constants/kubernetes.go, pkg/util/constants/postgresql.go
Add possibility to mount an extra memory volume to increase available shm. Fixes #426
=> Add shm_volume option

pkg/controller/node.go, run_operator_locally.sh
This reverts commit 4fa09e0dcbe556106beaed4078e6c2756245e931.
the PR #389 introduce unnecessary log bloat
=> Revert "Unify warnings about unmovable pods (#389)"

docs/reference/operator_parameters.md, manifests/configmap.yaml, pkg/cluster/cluster.go, pkg/spec/types.go, pkg/util/config/config.go, pkg/util/users/users.go, run_operator_locally.sh
=> [WIP] Add 'admin' option to create role

docs/reference/operator_parameters.md
AFAICT the parameter `enable_db_access` referred to in docs/reference/operator_parameters.md should really be `enable_database_access`.
=> Fix reference to enable_database_access in operator_parameters.md

pkg/cluster/cluster.go, pkg/cluster/pod.go
Diving into the migration failures we see that the logging is in parts confusing and not splitting "steps/process" messages from the action messages.
=> Modifying some of the logging to be more descriptive.

docs/developer.md
The endpoints with `/cluster/$team/$clustername` did not work for me.
After looking into the [apiserver.go](https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/apiserver/apiserver.go) file it seems to be `/clusters/$team/$namespace/$clustername`
=> Fixed endpoints description for debug API

pkg/controller/postgresql.go
This fixes https://github.com/zalando-incubator/postgres-operator/issues/448
After this patch creating a Postgres resource with missing teamId and then updating it with incorrect teamId, it  reports new error as expected:
```
infra-postgres-operator-dev-7658595fb-mjjvw main time="2019-01-10T15:19:26Z" level=debug msg="skipping \"ADD\" event for the invalid cluster: team name is empty" cluster-name=dev/acid-test-cluster pkg=controller
infra-postgres-operator-dev-7658595fb-mjjvw main time="2019-01-10T15:19:46Z" level=debug msg="skipping \"UPDATE\" event for the invalid cluster: name must match {TEAM}-{NAME} format" cluster-name=dev/acid-test-cluster pkg=controller
```
=> Report new Postgres CR error when previously incorrect one is being updated

docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/k8sres.go, pkg/controller/operator_config.go, pkg/util/config/config.go, run_operator_locally.sh
LoadBalancer services in bare metal configuration usually requires some annotations to overcome problem assigning external IP. This should help with that.
=> Added possibility to add custom annotations to LoadBalancer service.

manifests/configmap.yaml, manifests/minimal-postgres-manifest.yaml, manifests/postgres-operator.yaml, run_operator_locally.sh
1. Bump up Spilo and operator images
2. Run `acid-minimal-cluster` in the `default` namespace, add an option to run it in `test`
3. Fix the command for starting minikube (caused by changes in its API)
4. Add an option to replace the operator image without restarting the minikube; that greatly speeds up local testing as minikube restarts may take minutes.
=> Fix run operator locally

pkg/cluster/cluster.go
Problem is in  these 2 lines:
```go
c.setStatus(acidv1.ClusterStatusUpdating)
c.setSpec(newSpec)
```
former sets status in Kubernetes object and `c.Status` via embedded `acidv1.Postgresql`, but llatter one reverts `c.Status` to the one from Event, which for healthy cluster is `acidv1.ClusterStatusRunning` as a result c.Postgresql doesn't reflect latest known state of the object anymore.
When Update() finishes it's job it was  checking c.Status presumably to avoid unnecessary updates, which makes it skip updating status in Kubernetes.
Fixes https://github.com/zalando-incubator/postgres-operator/issues/467
=> Correctly report success in .status on Update

docs/reference/operator_parameters.md, manifests/configmap.yaml, pkg/cluster/k8sres.go, pkg/controller/node.go, pkg/util/config/config.go
1. implement #514 We use `ordered_ready` as the  default policy because it was used before and actually comes form the default Kubernetes stateful sets options' 
2. fix an error in logging master pod migration attempts
=> Set statefulset update and management policy explicitly

README.md
=> Rearrange the README.

Makefile
Remove unnecessary double quotes in the path value
=> Fix for broken Makefile

README.md, docs/administrator.md, docs/developer.md, docs/quickstart.md
Now that we offer a Helm chart, too, I felt it's time to split up the `formatted` text block with all the code snippets and comments in the quickstart.
Realized, that it's also contained in the README. Removed it there and inserted a link to the quickstart.
I've also updated the developer and admin docs to mention the Helm chart.
=> Updated quickstart and link from README

pkg/controller/controller.go
Fixes issue #528.
I wonder if the name could already be set in the init JSON literal.
=> set default name also for RoleBinding and roleRef

docs/developer.md
Something to point contributors to when adding features. Focuses on extending the configuration. Am I missing something?
resolves #532
=> Add paragraph on how to extend operator configuration in dev docs

pkg/cluster/k8sres.go
removes excessive syncing of stateful sets
=> fix statefulset sync

pkg/cluster/cluster.go
Discussed in https://github.com/zalando/postgres-operator/issues/566
=> fix: remove headless service config when deleting cluster

charts/postgres-operator/values.yaml, docs/administrator.md, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/database.go, pkg/controller/operator_config.go, pkg/util/config/config.go
Use the pod's configured dns search path, for clusters
where .svc.cluster.local is not correct.
=> database.go: remove hardcoded .svc.cluster.local dns suffix

pkg/controller/controller.go
Improves the rolebinding name to `"<serviceaccount>:<clusterrole>"`, and
does not overwrite clusterrole reference with serviceaccount name.
Suggested patch for #578 
Tested working for us, using configmap for configuration, with the default zalando-postgres-operator clusterrole name, and a custom podserviceaccountname.
=> decouple clusterrole name and serviceaccount name

docker/Dockerfile, manifests/postgres-operator.yaml
postgres-operator deployment template: 
Support running operator as non-root, and with readonly filesystem
[edit add description to content too]
=> postgres-operator deployment template: run operator as non-root, and with readonly filesystem

docs/user.md, manifests/user-facing-clusterroles.yaml
Fixes #584. Adds user facing clusterroles so kubectl get postgresql and kubectl create postgresql works for view and edit/admin default rolebindings.
=> rbac: add user-facing clusterroles

docs/reference/operator_parameters.md, pkg/controller/util.go
Operator proceeds to checking if CRD is present and ready,
and if not, only then it is a fatal error.
=> Not being able to register CRD is not a fatal error

pkg/cluster/k8sres.go
spilo depends on ReadOnlyRootFilesystem: false, but the operator does
not explicitly specify it. And a default pod security policy may change
the default to ReadOnlyRootFilesystem: true.
Explicitly specify ReadOnlyRootFilesystem: false so kubernetes can pick
a less restrictive policy the operator has access to.
=> specify ReadOnlyRootFilesystem: false for pod security policies

docs/reference/cluster_manifest.md, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/apis/acid.zalan.do/v1/util_test.go, pkg/cluster/k8sres.go
This is something which is useful together https://github.com/zalando-incubator/postgres-operator/pull/445 or sidecars when they get support of arbitrary volume mounts.
These containers might want to use volume for their own need, but it should not interfere with Spilo/Patroni container, so safest way is to use subPath in Patroni container.
This change is completely transparent for Patroni, paths in container remain the same and nothing changes from it's point of view.
=> Support subPath in generated container

charts/postgres-operator/values.yaml, docs/administrator.md, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/controller/operator_config.go, pkg/util/config/config.go
First initial commit for adding  cloud secrets to non cloud environment.
It ties to address #198
=> Add secret mount to operator

docs/quickstart.md, manifests/kustomization.yaml
Add ability to install the operator via kustomization as proposed in #607
=> Kustomization

docs/reference/operator_parameters.md
Looks like the anchor was changed in the K8S docs.
=> Update link for pod_antiaffinity_topology_key

docker/logical-backup/dump.sh, pkg/cluster/k8sres.go
export POD_NAMESPACE env var also for logical backup pod template and use it in `dump.sh`
adresses #616
=> Query namespaced K8s API in logical backup script

e2e/tests/test_e2e.py, pkg/cluster/k8sres.go
Label Logical Backup Pod with `application=spilo-logical-backup` to avoid interference with AntiAffitiny from StatefulSet.
Fixes #593
=> change app label for logical backup pod

.travis.yml, Makefile, README.md, delivery.yaml, docs/administrator.md, docs/developer.md, docs/diagrams/pod.tex, docs/index.md, docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, e2e/Dockerfile, e2e/Makefile, e2e/README.md, e2e/run.sh, e2e/tests/__init__.py, e2e/tests/test_e2e.py, pkg/util/config/config.go, run_operator_locally.sh, ui/operator_ui/spiloutils.py
- separate Makefile for e2e tests
- run.sh will pull operator and e2e-tests images
- bump kind version to 0.4.0
- small updates in developer docs and README (e.g. K8s everywhere)
=> make run.sh executable from within e2e

charts/postgres-operator/templates/clusterrole.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, manifests/complete-postgres-manifest.yaml, manifests/configmap.yaml, manifests/minimal-postgres-manifest.yaml, manifests/operator-service-account-rbac.yaml, manifests/postgres-operator.yaml, manifests/standby-manifest.yaml
=> bump to v1.2.0

docs/reference/cluster_manifest.md
=> Fix typo "hostssl"

charts/postgres-operator/templates/customrresourcedefinition.yaml, pkg/apis/acid.zalan.do/v1/crds.go
Show some more infos when listing `postgresql` or `OperatorConfiguration` resources. We can discuss in this PR which columns to print.
```
kubectl get pg                                         
NAME                TEAM   VERSION   PODS   VOLUME   CPU-REQUEST   MEMORY-REQUEST   AGE   STATUS
acid-test-cluster   ACID   10        2      1Gi      10m           100Mi            6s    Creating
kubectl get opconfig
NAME                                        IMAGE                                               CLUSTER-LABEL   SERVICE-ACCOUNT   MIN-INSTANCES   AGE
postgresql-operator-default-configuration   registry.opensource.zalan.do/acid/spilo-11:1.5-p9   cluster-name    operator          -1              2s
```
Closes #635
=> additional printer columns for CRDs

docs/reference/cluster_manifest.md
[minimal](../manifests/minimal-postgres-manifest.yaml)
and the
[complete](../manifests/complete-postgres-manifest.yaml)
Links don't work as the manifests directory is higher in the structure.
=> fix relative links to manifest files

pkg/cluster/cluster.go, pkg/cluster/util.go, pkg/controller/postgresql.go, pkg/util/k8sutil/k8sutil.go
If a cluster is deleted immediately after creation, fields of the `cluster` struct are empty when processing the DELETE event. The same might happen when a cluster doesn't get into the `Running` state at all.
fixes #551
=> Avoid orphaned objects on delete

charts/postgres-operator/templates/customrresourcedefinition.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml
Signed-off-by: Stefan Frye <frye@deitmer-it.de>
In certain scenarios (e.g., automated testing) it is helpful to be able to switch off CRD creation by the Helm chart. As CRDs are not automatically deleted on `helm delete`, we prefer to manage them separately.
=> Allow disabling of CRD creation

delivery.yaml
The kubectl-pg dependencies are currently not downloaded which leads to an error when calling `go test ./...`. As unit tests only live in the `pkg` directory at the moment we can also call `go test ./pkg/...`.
Adding `GO111MODULE=on` would also solve this problem, but we can leave it to PR #544 .
=> Limit go test to pkg folder

Makefile, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, e2e/Makefile, manifests/complete-postgres-manifest.yaml, manifests/configmap.yaml, manifests/minimal-postgres-manifest.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/util/config/config.go
1. build the operator image to be tested locally instead of fetching the same image from a registry
2. bump up Spilo, PG, and `kind` versions
=> fix e2e tests

pkg/util/patroni/patroni.go, pkg/util/patroni/patroni_test.go
Encapsulate IPv6 addresses in brackets.
Fixes `could not patch postgres parameters with a pod namespace/pod-0: could not make request: Patch http://ffff:ffff::1009:8008/config: invalid URL port \"ffff:1009:8008\`
Changing patroni configs now works properly.
```
time="2019-09-19T07:36:06Z" level=debug msg="calling Patroni API on a pod namespace/pod-0 to set the following Postgres options: map[max_connections:2000]" cluster-name=namespace/pod pkg=cluster
time="2019-09-19T07:36:06Z" level=debug msg="making PATCH http request: http://[ffff:ffff::1009]:8008/config" cluster-name=namespace/pod pkg=cluster
time="2019-09-19T07:36:06Z" level=debug msg="performing rolling update" cluster-name=namespace/pod pkg=cluster
```
=> Handle IPv6 k8s pods in Patroni URLs

pkg/controller/controller.go, pkg/controller/postgresql.go
For optimization purposes operator was creating a cache map to remember
if service accounts and role binding was deployed to a namespace. This
could lead to a problem, when a namespace was deleted, since this
cache was not synchronized. For the sake of correctness remove the
cache, and check every time if required service account and rbac is
present. In the normal case this introduces an overhead of two API calls
per an event (one to get a service accounts, one to get a role binding),
which should not be a problem, unless proven otherwise.
=> Remove service accounts cache

pkg/cluster/resources.go, pkg/cluster/volumes.go
Super minor change, just corrects a very minor spelling mistake in the function name.
Let me know if there is anything else required for this.
=> Fixing spelling mistake in delete PVC function name

charts/postgres-operator/templates/clusterrole.yaml, manifests/operator-service-account-rbac.yaml
Without this it fails with: `could not sync persistent volumes: could not sync volumes: could not resize the filesystem on pod \"testns/testdb-0\": could not get device and type for the postgres filesystem: could not execute: pods \"testdb-0\" is forbidden: User \"system:serviceaccount:postgres-operator:postgres-operator\" cannot create resource \"pods/exec\" in API group \"\" in the namespace \"testns\"`
=> charts: Add pods/exec permission

Makefile, delivery.yaml
to make sure test succeed when called from another project where operator is a dependency
=> enable GO111MODULE also on go test

docs/reference/operator_parameters.md
=> docs: Fix links on operator parameters reference

pkg/cluster/k8sres.go
additionally mounted secrets such us cloud or local credentials should also be available for logical backups pods
=> pass additionalSecretMount to logical backup pod

docker/logical-backup/dump.sh, manifests/operator-service-account-rbac.yaml, pkg/cluster/k8sres.go
Why complicated querying for the cluster name label when we can inject it into the logical backup pod?
Closes: #718 
Fixes: #692 
Fixes: #642 
Thanks to
@bchrobot pointing out the limitation for calling resources only on the default namespace,
@OlleLarsson for checking config call and
@yujunz for raising the awareness of not using a hard-coded cluster name label
=> inject cluster name label into logical backup pod

pkg/cluster/resources.go, pkg/util/constants/kubernetes.go
when service type is changed, operator deletes the current service and tries to create a new one immediately, which fails as deletion doesn't happen that fast. This PR reuses the same retry/wait logic from StatefulSet deletion. 
After this part of `updateService`, creation order of endpoint and service is also reversed to avoid connection problems while syncing roles in the next step
fixes #713
=> fix errors when changing service type

docker/logical-backup/dump.sh
Fix of `dump.sh` script in the logical_backup docker image. The `aws` command was not correctly quoted when using a custom endpoint url.
=> fix backup docker image

hack/update-codegen.sh, hack/verify-codegen.sh
Small tweak. Make the shebang work on NixOS and other non-Ubuntu systems.
=> hack: update shebang

manifests/operator-service-account-rbac.yaml
Closes #256
`bind` for cluster roles is too powerful and not needed anymore
=> Remove bind verb and explain privileges

charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, manifests/postgres-operator.yaml
the current `v1.3.0` image does not reflect the `latest` state. This PR fixes it.
=> Update release image

docker/logical-backup/Dockerfile, docker/logical-backup/dump.sh
* enable and disable tracing only for dump - S3 upload pipeline to avoid logging tokens
* use PIPESTATUS to print all error codes
* include Pg 12 client
* remove tailing `/` for PG_DIR env variable
fixes #790
=> reduce tracing of dumps and include Pg12

pkg/cluster/k8sres.go
If `min_instances` is configured to be > 1 (in case you always want a replica), standby cluster end up with two pods, which is currently not properly supported. Workaround would be to copy secrets from the source cluster.
=> standby clusters can only have 1 pod for now

pkg/apis/acid.zalan.do/v1/util_test.go
The [Unmarshall function][1] on the encoding/JSON default library returns
different errors for different go versions. On Go 1.12, the version used
currently on the CI system it returns `json: cannot unmarshal number into
Go struct field PostgresSpec.teamId of type string`. On Go 1.13.5 it
returns `json: cannot unmarshal number into Go struct field
PostgresSpec.spec.teamId of type string`. The new version includes more
details of the whole structure being unmarshalled.
This commit introduces the same error but one level deeper on the JSON
structure. It creates consistency across different Go versions.
[1]: https://godoc.org/encoding/json#Unmarshal
---
The Run method of T allows defining subtests creating hierarchical tests.
It provides better visibility of tests in case of failure. More …
=> Change error computation on JSON Unmarshal and create subtests on table test scenarios

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, docs/user.md, e2e/tests/test_e2e.py, manifests/complete-postgres-manifest.yaml, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgres-operator.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/cluster.go, pkg/cluster/sync.go, pkg/controller/operator_config.go, pkg/util/config/config.go
Do not simply error out, but raise limits to configured minimum limits.
Lower limits for operator pod and default limits for pods.
=> make minimum limits boundaries configurable

charts/postgres-operator/templates/service.yaml
I added a k8s service (Helm template) for exposing the operator api. I needed it for running the UI as a separate pod.
=> add service for exposing operator api

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docker/logical-backup/dump.sh, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/k8sres.go, pkg/controller/operator_config.go, pkg/util/config/config.go
Hi! Following the example of #628 I've added a setting for the region when configuring logical backups. With some S3-compatible services like Scaleway you need to specify the region as well as the endpoint in the aws upload command, otherwise the upload fails. I found this while investigating with the dump.sh script and found that I had to add `--region <region>` to the aws command for the upload to succeed. Tested many times.Hope this is OK. Thanks!
=> Add region setting for logical backups to non-AWS storage

charts/postgres-operator/crds/postgresqls.yaml, docs/administrator.md, docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, e2e/README.md, e2e/tests/test_e2e.py, manifests/complete-postgres-manifest.yaml, manifests/postgres-manifest-with-service-annotations.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/apis/acid.zalan.do/v1/util_test.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go
The [operator parameters][1] already support the `custom_service_annotations` config. With this parameter is possible to define custom annotations that will be used on the services created by the operator. The `custom_service_annotations` as all the other [operator parameters][1] are defined on the operator level and do not allow customization on the cluster level. A cluster may require different service annotations, as for example, set up different cloud load balancers timeouts, different ingress annotations, and/or enable more customizable environments.
This commit introduces a new parameter on the cluster level, called `serviceAnnotations`, responsible for defining custom annotations just for the services created by the operator to the specifically defined cluster. It allows a mix of …
=> Add ServiceAnnotations cluster config

e2e/tests/test_e2e.py
otherwise it will not wait for the right replica
plus raise min memory limit to fasten tests (decompressing image)
=> specify cluster in e2e taint test

pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/controller/operator_config.go
I tried using the default CRD-based operator configuration from [here](https://github.com/zalando/postgres-operator/blob/master/manifests/operatorconfiguration.crd.yaml), but it failed:
```
time="2020-02-05T13:48:02Z" level=fatal msg="unable to read operator configuration: could not get operator configuration object \"postgres-operator-configuration\": v1.OperatorConfiguration.Configuration: v1.OperatorConfigurationData.Kubernetes: v1.KubernetesMetaConfiguration.MasterPodMoveTimeout: readUint64: unexpected character: \xff, error found in #10 byte of ...|timeout\":\"20m\",\"oaut|..., bigger context ...|\"enable_sidecars\":true,\"master_pod_move_timeout\":\"20m\",\"oauth_token_secret_name\":\"postgresql-operato|..." pkg=controller
```
From what I can tell,  attempting to unmarshal the …
=> Fix MasterPodMoveTimeout field that cannot be unmarshalled

charts/postgres-operator-ui/templates/serviceaccount.yaml, charts/postgres-operator/templates/clusterrole.yaml, manifests/operator-service-account-rbac.yaml, pkg/cluster/cluster.go, pkg/controller/controller.go, pkg/util/k8sutil/k8sutil.go, ui/manifests/ui-service-account-rbac.yaml
TL;DR: first change RBAC apiVersion, then enable namespaced roles
Deploying the operator with namespaced roles support (see #786) creates the `postgres-pod` role in each namespace. If we want to bind to a clusterrole instead we must then overwrite the [internal definition](https://github.com/zalando/postgres-operator/blob/3b10dc645dd3f4112df7d15042f335b86c01b3fc/pkg/controller/controller.go#L199) by setting the `pod_service_account_role_binding_definition` in the configmap. So we should first configure the operator and then deploy.
And here's the problem: When changing the RBAC version within the same PR, the apiVersion in the role definition must be of version `v1` do be supported by the new operator. But the current operator only understands `v1beta1`. Everything could be done in one …
=> switch to rbac/v1

pkg/util/k8sutil/k8sutil_test.go
The code added on #818 depends on map sorting to return a static reason
for service annotation changes. To avoid tests flakiness and map sorting
the tests include a `strings.HasPrefix` instead of comparing the whole
string. One of the test cases,
`service_removes_a_custom_annotation,_adds_a_new_one_and_change_another`,
is trying to test the whole reason string.
This commit replaces the test case reason, for only the reason prefix.
It removes the flakiness from the tests. As all the cases (annotation
adding, removing and value changing) are tested before, it's safe to
test only prefixes.
Also, it renames the test name from `TestServiceAnnotations` to
`TestSameService` and introduces a better description in case of test
failure, describing that only prefixes are tested.
=> Fix test flakiness on TestSameService

ui/requirements.txt
since werkzeug 1.0.0 flask has [problems](https://github.com/pallets/werkzeug/issues/1714). Pinning last version before 1.0.0
logs from UI pod after applying the manifests
```
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/operator_ui/__main__.py", line 1, in <module>
from .main import main
File "/operator_ui/main.py", line 25, in <module>
from flask_oauthlib.client import OAuth
File "/usr/lib/python3.6/site-packages/flask_oauthlib/client.py", line 18, in <module>
from werkzeug import url_quote, url_decode, url_encode
ImportError: cannot import name 'url_quote'
```
=> added pinned werkzeug dep to UI requirements

charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, manifests/complete-postgres-manifest.yaml, manifests/configmap.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/util/config/config.go
[including](https://github.com/zalando/spilo/releases/tag/1.6-p2) latest minors of all supported Postgres versions
and more
=> bump spilo version to latest release

docs/administrator.md, docs/reference/operator_parameters.md, docs/user.md, pkg/cluster/k8sres.go
If somebody is already running a standby with more than one instance, the operator should not terminate the replicas, but give a warning instead that we recommend `1`.
The docs on standby clusters should also be more clear now on what is possible and how to set it up.
=> be more permissive with standbys

delivery.yaml, ui/Makefile
let UI use the same tag as the operator
=> align UI pipeline with operator

manifests/postgresql-operator-default-configuration.yaml
The documentation states that the default operator REST service is at port `8080`, but the current default CRD based configuration is `8008`. Changing the default config to match documentation.
=> Change `logging_rest_api.api_port` to `8080` instead of `8008`

e2e/tests/test_e2e.py, pkg/controller/node.go
add test case for setting node readiness label + improve log output of `moveMasterPodsOffNode` function
sort all e2e tests in the order how they are executed: alphabetically
=> add e2e test for node readiness label

e2e/tests/test_e2e.py
do not leave the pod distribution test with a cluster failing over, but wait for both instances to be ready
=> e2e: wait for pods after disabling anti affinity

pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
ClusterDomain should have json:omitempty option so that the default value of cluster.local is assumed when the parameter is omitted from the OperatorConfiguration
=> add json:omitempty option to ClusterDomain

kubectl-pg/cmd/list.go, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/cluster/sync.go
Changing the Postgres version can currently break the cluster. It is caught on `Update` but not on `Sync`.
Retrieving the current PG version on sync is only possible through the `bin_dir` setting in the `SPILO_CONFIGURATION` env variable of the `postgres` container. Extracting the version is done with `Sscanf` to make it work even when the bin path template is configurable, as suggested in #554.
This PR also adds `PostgresParam` where `PgVersion` field is read
=> omit PgVersion diff on sync

pkg/util/util.go
The current password generation algorithm is extremely deterministic, due to being based on the standard random number generator with a deterministic seed based on the current Unix timestamp (in seconds).
This can lead to a number of security issues, including:
* The same passwords being used in different Kubernetes clusters if the operator is deployed in parallel. (This issue was discovered because of four deployments having the same generated passwords due to automatically being deployed in parallel.)
* The passwords being easily guessable based on the time the operator pod started when the database was created. (This would typically be present in logs, metrics, etc., that may typically be accessible to more people than should have database access.)
This PR attempts to fix this issue by …
=> Use cryptographically secure password generation

charts/postgres-operator/templates/_helpers.tpl, charts/postgres-operator/templates/clusterrole-postgres-pod.yaml, charts/postgres-operator/templates/configmap.yaml, charts/postgres-operator/templates/deployment.yaml, charts/postgres-operator/templates/operatorconfiguration.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml
The PR fixes #875 and also adds the controller ID feature introduced with #802.
The pod service account name will be `postgres-pod` by default, but it can also be generated by helm. The controller ID is not defined by default.
=> enable controllerID for chart and allow configurable pod cluster role

docs/user.md, manifests/complete-postgres-manifest.yaml, pkg/cluster/k8sres.go
Adds OpenShift compatibility by removing forced injection of fsGroup.
In it's current format, there is no workaround to use TLS in non-priviledged, non-root OpenShift, where fsGroup **must not be set** , as it's dynamically allocated at creation time.
Solves: https://github.com/zalando/postgres-operator/pull/798#issuecomment-605201260
@zimbatm and @FxKu - please review.
=> TLS - add OpenShift compatibility

pkg/cluster/k8sres_test.go
as it's not automatically anymore the unit test should put the expected 103 group in the Config
=> fix TestTLS

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/resources.go, pkg/controller/operator_config.go, pkg/util/config/config.go
It's not supported, neither it's a best practice. Also fix potential
null pointer access.
=> Prevent superuser from being a connection pool user

pkg/cluster/cluster.go, pkg/cluster/sync.go, pkg/cluster/sync_test.go, pkg/cluster/types.go
There is a possibility to pass nil as one of the specs and an empty spec
into syncConnectionPooler. In this case it will perfom a syncronization
because nil != empty struct. Avoid such cases and make it testable by
returning list of syncronization reasons on top together with the final
error.
=> Prevent empty syncs of connection pool

pkg/cluster/cluster.go, pkg/cluster/sync.go
code was still trying to remove endpoints even when kubernetes_use_configmaps was true (continuation of https://github.com/zalando/postgres-operator/pull/887)
It is desired to inhibit the delete as well, as there might be no perms to make any actions against them, so, to be on the safe side, we are inhibiting this delete when it is not required.
=> when kubernetes_use_configmaps -> skip further endpoints actions even delete

charts/postgres-operator/templates/clusterrole.yaml, manifests/operator-service-account-rbac.yaml, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres_test.go, pkg/cluster/resources_test.go, pkg/cluster/sync.go, pkg/cluster/sync_test.go, pkg/controller/controller.go, pkg/controller/postgresql.go, pkg/util/k8sutil/k8sutil.go
Currently the only "feedback" the user or creator of a _postgresql_ custom resource receives is the status. While the operator does produce quite a bit of log, this is not suitable to point users to in order for them to find issues with their particular cluster.
This PR shall enable to operator to (also) send events which are promoted by the Kubernetes documentation (https://kubernetes.io/docs/tasks/debug-application-cluster/#example-debugging-pending-pods) to help debugging issues with a resource and to search for messages from controllers handling this resource.
As this shall be a first cut, I might not have added enough events or even have added events that are too noisy. My intention was to report back certain aspects of the life-cycle:
- Creation with the individual steps / resources …
=> Emit K8S events to the postgresql CR as feedback to the requestor / user

manifests/complete-postgres-manifest.yaml, pkg/apis/acid.zalan.do/v1/postgresql_type.go
related to PR #736:
It is not possible to specify a `volumeSource` based on the given cluster manifests examples and the documentation: The name of the json field within the `AdditionalVolume` struct is `volume`. The name specified in the CRD is `volumeSource`: https://github.com/zalando/postgres-operator/blob/3c91bdeffadb5ec736a63548b5ffa08517c59de8/manifests/postgresql.crd.yaml#L45-L48
=> fix typo in additionalVolume struct

pkg/cluster/k8sres_test.go
=> fix params in function call in tests

charts/postgres-operator-ui/templates/service.yaml, charts/postgres-operator-ui/values.yaml
Added support for specifying a nodePort value for the postgres-operator-ui service when the service type is NodePort.
=> Allow nodePort value for the postgres-operator-ui service

charts/postgres-operator/templates/clusterrole.yaml, docs/user.md, manifests/operator-service-account-rbac.yaml, pkg/controller/controller.go
to make events more visible
plus, as recommended by our K8s team, "client-go needs to be able to see existing events and patch/update them"
=> set event broadcasting to Infof and update rbac

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go
As we can clone or restore clusters, new secrets will get created and passwords get reset. Issue from #173 is obsolete by now.
=> delete secrets of system users too

pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
Related to https://github.com/zalando/postgres-operator/issues/979
Changing the order of which env variables are added to sidecars containers to support referencing common fields that are injected in other env vars.
=> Changed order of sidecar env vars

ui/manifests/service.yaml
Currently, the deployment manifest specifies two labels: `name` and `team`.
This fixes the service not matching the deployed pods by chosing a correct selector.
=> Make selector match labels defined in the deployment

pkg/cluster/cluster.go
addresses #988
we still need to check, if TLS and spiloFSGroup can be added at the same time, with this diff present
=> trigger rolling update when securityContext of PodTemplate changes

charts/postgres-operator/crds/postgresqls.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go
If volume section is left out in manifest, cluster setup fails. So CRD validation should mark this field as required.
=> include volume in list of required fields

pkg/apis/acid.zalan.do/v1/marshal.go, pkg/cluster/cluster.go, pkg/cluster/sync.go, pkg/controller/controller.go, pkg/controller/postgresql.go, pkg/util/k8sutil/k8sutil.go
if the cluster name does not start with the `teamId` we are currently skipping the add event, which makes it hard to track the error from the UI. It is emitted neither to worker logs nor to K8s events. The `PostgresClusterStatus`, although set during marshaling, remains empty.
The PR does not skip the addEvent but will process it until the cluster would get created. This allows to show the error in logs accessible from UI and to record a K8s event with a working `ObjectReference`.
=> skip creation later to improve visibility of errors

docs/quickstart.md
I was not sure why you guys were making this more difficult then it is :laughing:
=> Tiny Getting Started documentation fix: port-forward service instead of pod

go.mod, pkg/cluster/cluster.go, pkg/util/users/users.go, pkg/util/util.go, pkg/util/util_test.go
Implemented scram-sha-256 to encrypt the password.
=> Use scram-sha-256 hash if postgresql parameter password_encryption set to do so.

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/administrator.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/controller/operator_config.go, pkg/util/config/config.go
Currently the Operator allows to configure a ConfigMap which key-value pairs are then added to the pod environent variables (https://postgres-operator.readthedocs.io/en/latest/administrator/#custom-pod-environment-variables).
Depending on your clusters RBAC roles and settings, ConfigMaps are usually accessible quite freely (compared to secrets, which can be restricted independently) and having the value exposed in the pod spec adds to this issue of exposing credentials to access all your valuable data.
This PR adds the same functionality, but using a Secret as a source and references to the keys in the secret instead of copying the key-value pairs - like suggested in the two issues https://github.com/zalando/postgres-operator/issues/480 and …
=> Allow pod environment variables to also be sourced from a secret

charts/postgres-operator-ui/templates/deployment.yaml
This PR addresses #1081.
fixes #978
This change allows the `targetNamespace` to be set to `"*"` to watch all namespaces, and maintains the ability to set the `targetNamespace` to a particular namespace of type string.
=> chart ui: fix target namespace to allow '*'

pkg/cluster/k8sres_test.go
PR #946 changed the order of Pod env variables to allow overwriting by additional variables coming from ConfigMap or Secret. Thus the `DCS_ENABLE_KUBERNETES_API` or `ETCD_HOST` variables now come before the additional variables
=> fix index in TestGenerateSpiloPodEnvVars

pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
make sure the order of env variables returned from `getPodEnvironmentConfigMapVariables` and `getPodEnvironmentSecretVariables` is the same for the slices defined in the tests
=> fix random order for pod environment tests

charts/postgres-operator/crds/operatorconfigurations.yaml, e2e/tests/test_e2e.py, manifests/infrastructure-roles-new.yaml, manifests/infrastructure-roles.yaml, manifests/operatorconfiguration.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/controller/util.go, pkg/controller/util_test.go, pkg/util/config/config.go
Current master only allows to set one of the two infrastructure roles options. If `infrastructure_roles_secrets` is set, `infrastructure_roles_secret_name` is ignored. However, as the new option doesn't allow "templating", so configmap users might still want to use old option but also being able to reference another secret with the new flexibility of choosing the keys.
This PR also fixes a small "bug": When using the new configmap option one had to specify a `rolekey`. But it could be that this info isn't available. CRD validation also doesn't enforce it.
=> allow using both infrastructure_roles_options

go.mod, go.sum, pkg/cluster/cluster.go, pkg/cluster/resources.go, pkg/cluster/sync.go
This PR sets secrets on SYNC, so that they can be deleted.
On connection pooler deletion the corresponding secret is now removed via API call. Because of the way roles and secrets are synced with the `needCoonectionPooler` condition, the pooler user and secret are no longer set after deletion. But resources would still be there. For the database user it's fine - operator does not delete those in general - but the secret should go.
=> Remove all secrets on delete incl. pooler

manifests/postgres-operator.yaml, pkg/cluster/cluster.go, pkg/util/constants/roles.go, pkg/util/users/users.go
fixes #1014
When creating databases through the `preparedDatabases` feature the `search_path` is not configured hence all created roles need to put schema qualifiers in their queries. But, the existing `PgUser` user type already has a field `Parameters` to allow for setting `search_path` individually. Even code for altering the role has already been there, although it wasn't used probably.
This PR defines a default `search_path: "$user"` for each role (note `public` is not included) and then appends all schemas, if it's a `<dbname>_[owner|reader|writer]` role or only one schema when it's a  `<dbname>_<schema>_[owner|reader|writer]` role.
Adding databases with two schemas will have the following settings:
```
preparedDatabases:
bar:
schemas:
prod: {}
audit: {}
SELECT r.rolname, d.datname, …
```
=> set search_path for default roles

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/administrator.md, docs/reference/operator_parameters.md, e2e/requirements.txt, e2e/tests/test_e2e.py, manifests/complete-postgres-manifest.yaml, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/controller/controller.go, pkg/controller/operator_config.go, pkg/controller/postgresql.go, pkg/controller/postgresql_test.go, pkg/util/config/config.go
Right now a Postgres cluster can be easily removed with `kubectl delete pg acid-minimal-cluster`. If clusters are called very similar it might happen that one accidently removes the wrong resource. While it could be recovered from S3 pretty quickly (depending on the size, of course) a few more steps might be necessary to get back to normal operating mode.
To avoid all the stress, this PRs introduces a simple delete protection mechanism, that checks for existing annotations in the manifest before allowing the delete process to continue. Actually, we would assume this is something to be set in the K8s infrastructure, which blocks a delete request already at the ApiServer level. With this approach here, the CR still gets removed but all managed child resources remain. Either if the cluster …
=> allow delete only if annotations meet configured criteria

pkg/cluster/database.go, pkg/cluster/sync.go
Hi,
Problem was: defer should not be used in for loops. 
Link:  https://stackoverflow.com/questions/45617758/defer-in-the-loop-what-will-be-better 
Fixes #1130 
```
time="2020-09-11T13:08:11Z" level=debug msg="syncing roles" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=debug msg="closing database connection" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="syncing databases" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="creating database \"a3db\" owner \"a3db_owner\"" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="creating database \"a4db\" owner \"a4db_owner\"" cluster-name=kafka-fix/postgres-sebpg3 …
```
=> Fixes #1130

.travis.yml, delivery.yaml, manifests/configmap.yaml, manifests/postgres-pod-priority-class.yaml, pkg/cluster/cluster.go
Priority classes are immutable. One option to change a priority class for existing pods is to delete it and then submit the newly configured class under the same name. We deem this approach as too dangerous because in the meantime no Postgres pod will be able to start.
So we take the alternative approach  and rely on the existing Sync machinery to do the rolling update of existing pods.
=> Compare Postgres pod priority on Sync

README.md
remove outdated GSOC info
We did not apply in 2020
=> remove outdated GSOC info

.travis.yml, charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/templates/configmap.yaml, charts/postgres-operator/templates/operatorconfiguration.yaml, charts/postgres-operator/templates/postgres-pod-priority-class.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, go.mod, go.sum, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/util/config/config.go
#1136 was merged but this new config option wasn't covered in sample manifests and helm chart.
This PR also adds examples for pod priority class in helm chart and updates travis and go modules.
=> Cleanup config examples

pkg/cluster/k8sres.go
Right now there are no readiness probes defined for connection pooler,
which means after a pod restart there is a short time window (between a
container start and connection pooler starting listening to a socket)
when a service can send queries to a new pod, but connection will be
refused. The pooler container is rather lightweight and it start to
listen immediately, so the time window is small, but still.
To fix this add a readiness probe for tcp socket opened by connection
pooler.
=> Readiness probe

e2e/exec.sh, e2e/tests/test_e2e.py, pkg/cluster/cluster.go, pkg/cluster/database.go, pkg/cluster/sync.go
Apparently lookup function installation process is somewhat fragile right now.
It seems that it happens because a connection to an original db could be
somehow reused when we iterate over available databases, and the required
pooler appliance is installed into a wrong db (does it happen due to some
golang optimization reshuffling the code?). To prevent that and make the
implementation more robust, put more debug logging about installation process,
close connection before opening a new one and check to which database we
actually connected to. One more minor fix is to reset stmtBytes, as it was
accumulating stuff in between (which does not lead to any issues, as appliance
queries are idempotent, but still).
Fixes #1060
=> Lookup function installation

pkg/controller/controller.go
The function of  initPodServiceAccount() has been invoked at line 289, Remove repeated initialization of Pod ServiceAccount
=> Remove repeated initialization of Pod ServiceAccount

charts/postgres-operator/crds/postgresqls.yaml, docs/user.md, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go
Because otherwise cluster creation will silently fail when label length is exceeded (e.g. cluster name + random revision value)
=> add maxLength constraint for CRD

pkg/cluster/k8sres.go
Hello. If I understand correct, secret must be located in the same namespace as the postgresql cluster manifest.
=> Fixed PodEnvironmentSecret location namespace

pkg/controller/node.go, pkg/controller/node_test.go
in case there is no ready label defined, an unschedulable should make a node not ready
=> fixed case where, no ready label is defined, but node is unscheduable

charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, docs/user.md, manifests/configmap.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/controller/controller.go, pkg/controller/operator_config.go, pkg/util/config/config.go
better disable by default to avoid polluting operator logs
=> disable PostgresTeam by default

docker/Dockerfile, e2e/Makefile, e2e/README.md, e2e/scripts/watch_objects.sh, e2e/tests/k8s_api.py, e2e/tests/test_e2e.py
* More waits for cluster to be ok at end of test
* Added curl to operator image to allow getting API without port forward and stuff.
=> Improving e2e more

pkg/controller/util.go
only append once after the roleDescr checks. Should solve the `Conflicting infrastructure roles` error which one could see in the debug logs on operator start up
=> fix redundant appending of infrastructure roles

e2e/README.md, e2e/tests/k8s_api.py, e2e/tests/test_e2e.py, pkg/cluster/cluster.go
```bash
ERROR: no nodes found for cluster "postgres-operator-e2e-tests" 
```
during e2e test runs
=> Update e2e pipeline

charts/postgres-operator/templates/clusterrole.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, manifests/configmap.yaml, manifests/operator-service-account-rbac.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/cluster/cluster.go, pkg/cluster/sync.go, pkg/cluster/volumes.go, pkg/cluster/volumes_test.go
Risizing volumes by updating the PVC storage field has been introduced with #958. However the UPDATE event wasn't covered. Using `pvc` mode requires more privileges than what we currently list in the operator cluster role. In the helm chart we can arrange the RBAC nicely by checking the `storage_resize_mode` setting.
This PR also changes the `storage_resize_mode` in example manifests and charts to `pvc`. The internal default however remains `ebs`.
=> check resize mode on update events

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/crds/postgresqls.yaml, charts/postgres-operator/crds/postgresteams.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql.crd.yaml, manifests/postgresteam.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go
With #746 we switched the CRDs to `v1`. It seems that this api version does require to explicitly enable preserving unknown fields (e.g. whenever we allow full specs). Plus, the toggle moved from `crd.spec` to the schema.
This PR will also register the Postgres Operator CRDs in the `all` category, so that they are listed when `kubectl get all` is executed.
fixes #1206
=> CRD: preserve unknown fields and add to all category

charts/postgres-operator-ui/templates/deployment.yaml, charts/postgres-operator-ui/values.yaml
To use the Postgres Operator UI Helm Chart with a private docker registry, I was forced to transfer the imagePullSecret parameter of the Postgres Operator Helm Chart to the Postgres Operator UI Helm Chart.
I have no experience with GITHub yet, but would like to contribute the change.
Related to #1210
=> add operator ui helm chart value imagePullSecret

charts/postgres-operator/crds/postgresqls.yaml, docs/reference/cluster_manifest.md, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/cluster/k8sres.go
Hey there,
This is an updated, rebased continuation of Micah Coletti's PR allowing specification of an alternative scheduler.
If there is additional work that needs to be done on this to meet a standard deserving of merging, I'm up for it.
Would really appreciate involvement and direct answer if this is something that could become part of the postgres operator as it is a blocking issue for us.
Thank you for the great work on the project!
=> Add scheduler name support - [Update #990]

pkg/cluster/sync.go
Otherwise this message gets lost in the log output though when a secret is malformed.
=> raise log level for malformed secrets

pkg/cluster/connection_pooler.go
Use PodRoleLabel to get the correct label.
=> Avoid hard-coded spilo-role

pkg/apis/acid.zalan.do/v1/postgresql_type.go
I use the PostgreSQL type to configure a struct instance in golang to create the resource in the k8s cluster.
To create the https://github.com/zalando/postgres-operator/blob/master/manifests/minimal-postgres-manifest.yaml in golang it is necessary to add some more `omitempty` annotations to unset values.
Closes #1221
=> add to postgresql_type.go omitempty annotation

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, e2e/tests/k8s_api.py, e2e/tests/test_e2e.py, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/cluster/connection_pooler.go, pkg/cluster/k8sres.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/cluster/util_test.go, pkg/cluster/volumes_test.go, pkg/controller/operator_config.go, pkg/controller/postgresql.go, pkg/controller/util.go, pkg/util/config/config.go, pkg/util/k8sutil/k8sutil.go
In preparation for an inherited annotations feature, similar to inherited labels, to estimate how much it would take.
=> Support inherited annotations for all major objects

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/k8sres.go, pkg/controller/operator_config.go, pkg/util/config/config.go
new config option `enable_spilo_wal_path_compat` sets `ENABLE_WAL_PATH_COMPAT` in database pods
=> new env var for backwards compatability between spilo 12 and 13

kubectl-pg/cmd/util.go, pkg/cluster/cluster.go, pkg/cluster/connection_pooler_test.go, pkg/cluster/sync.go, pkg/controller/node_test.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/k8sutil_test.go
trigger rolling update if `SecurityContext` of container change, e.g. switching `spilo_privieleged` config option
this PR updates some log messages as well
=> diff SecurityContext of containers

pkg/cluster/cluster.go
Like the other resources, services, etc. sync statefulset when postgres version is upgraded.
=> Sync sts at pgversion upgrade

docker/Dockerfile
The MAINTAINER field has been deprecated for dockerfiles. https://docs.docker.com/engine/reference/builder/#maintainer-deprecated 
This PR updates to use the recommended LABEL field
=> update deprecated MAINTAINER field

charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/k8sres.go, pkg/controller/operator_config.go, pkg/util/config/config.go
Operator currently prepends the `logical-backup-` prefix to the name of  a CronJob doing the backup.
The prefix proved to be too long as it counts towards the name length limit imposed by k8s.
This patch makes the prefix configurable.
Automatic job renaming after prefix change is out of scope. Operator will automatically create a new job with the updated  prefix. The old job will stay around and has to be deleted manually. Logical backup jobs for `$CLUSTERNAME` are visible with
```bash
kubectl get cronjobs -l application=spilo,cluster-name=$CLUSTERNAME
``` 
Operator currently does not assign any specific labels to the jobs.
=> add a prefix for the name of a logical backup job

ui/operator_ui/spiloutils.py
Pods from enabled connection pooler also receive the `spilo-role=master` label. Therefore, only fetching pods by the cluster name would return too many labeled masters hence showing in the UI that the master isn't ready.
=> [UI] on read_pods filter only spilo pods

pkg/cluster/pod.go
e2e tests reveal operator is sometimes too fast to fetch  Patroni state. A few retires can help to alleviate the issue.
=> wrap getting Patroni state into retry

docs/reference/operator_parameters.md
Amends documentation to match recent changes to worker defaults: https://github.com/zalando/postgres-operator/pull/1004
=> Update workers to the new default

charts/postgres-operator/crds/operatorconfigurations.yaml, manifests/operatorconfiguration.crd.yaml
defaults -> default
Noticed the typo because I got an error while trying to update the CRD in my cluster
=> Fix typo in operatorconfigurations CRD

pkg/cluster/util.go
`getTeamMembers` should also work for other teams associated to a cluster, e.g. superusers, additional teams etc.
=> allow additional members from other teams

docs/user.md
closes #1316 
the quickstart is not changed as the host variable (PGHOST) is set there - so `-h` is not necessary
=> add host info to connection docs

charts/postgres-operator/templates/clusterrole-postgres-pod.yaml, charts/postgres-operator/templates/clusterrole.yaml, manifests/operator-service-account-rbac.yaml, pkg/cluster/k8sres.go
in the process of switching all pods to non-privileged pods the `use` privilege for a `privileged` PodSecurityPolicy is obsolete. However, Pods holding this privilege before might still escalate to such a PSP and will then face issues when the psp privilege is missing in the RBAC. Setting `AllowPrivilegeEscalation: false` on the container's securityContext should prevent this. The value will be based on what's configured for `spilo_privileged`.
=> set AllowPrivilegeEscalation on container securityContext

charts/postgres-operator/crds/postgresqls.yaml, docs/developer.md, docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, go.mod, go.sum, manifests/complete-postgres-manifest.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/cluster/sync.go, pkg/cluster/volumes.go, pkg/cluster/volumes_test.go, pkg/util/volumes/ebs.go, pkg/util/volumes/volumes.go
Enable AWS gp3 support in manifest, allowing configuration of `IOPS` and `Throughput`  and `Size`.
Potentially includes full support for EBS volume types with that. Thus `ìo2`.
=> Full AWS gp3 support for iops and througput config.

charts/postgres-operator/templates/deployment.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, manifests/complete-postgres-manifest.yaml, manifests/postgres-operator.yaml, pkg/cluster/connection_pooler.go
#1326 has added `allowPrivilegeEscalation` field to postgres containers, but operator and pooler containers might need it, too, since the service account they have used so far holds or has hold the `use` privilege for a `privileged` PSP.
This PR also introduces configuring the operator container's `securityContext` in the helm chart.
=> set allowPrivilegeEscalation for deployment templates

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, e2e/tests/k8s_api.py, e2e/tests/test_e2e.py, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/controller/operator_config.go, pkg/util/config/config.go
allow users to configure capabilities for postgres containers
=> configurable container capabilities

.github/workflows/run_tests.yaml
This commit attempts to fix the CI issues by upgrading the checkout
action to v2. This fix is documented by the coverallsapp upstream.
=> Fix CI Pipeline

pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
* pre-allocate cap for slice structure
* if clause is no needed because access slice with range, and kubelet also use range
method to get each capability so there is no side-effect
Signed-off-by: Jeff Zvier <zvier20@gmail.com>
=> code optimization for generateCapabilities

docker/logical-backup/Dockerfile
operator pipeline is currently failing because of:
```
Collecting cryptography>=3.2 (from pyOpenSSL>=0.13->gsutil)
Downloading https://files.pythonhosted.org/packages/f8/04/51dc8a4ccb37b69a4e165a94837f70653b0b6ca49a6346361062b1f6bb09/cryptography-3.4.3.tar.gz (545kB)
Complete output from command python setup.py egg_info:
=============================DEBUG ASSISTANCE==========================
If you are seeing an error here please try the following to
successfully install cryptography:
Upgrade to the latest pip and try again. This will fix errors for most
users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
=============================DEBUG ASSISTANCE==========================
Traceback (most recent call last):
File "<string>", line 1, in <module>
File …
```
=> [logical-backup] upgrade pip to latest version to avoid broken deps

pkg/util/config/config.go
This commit fixes a typo in the operator's configuration that would lead to the configs spilo_runasuser and spilo_runasgroup to be ignored.
fixes #1359
=> Fix operator configs runasuser and runasgroup

pkg/cluster/sync.go
=> Fix volume sync order.

pkg/cluster/k8sres.go, pkg/cluster/util.go, pkg/cluster/util_test.go
K8s cronjobs must be no longer than 52 characters. This fixes the issue of backup cronjobs not being created for DBs with long names.
=> Truncate cronjob name at 52 characters

docs/quickstart.md
add info on k3s 🙏🏼 
closes #1292
=> update quickstart to add k3d

e2e/tests/test_e2e.py, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/util.go, pkg/controller/controller.go, pkg/controller/util.go, pkg/teams/postgres_team.go, pkg/teams/postgres_team_test.go
when a PostgresTeam map is updated with more teams/users, it's immediately reflected in the controller's pgTeamMap (can be seen from logs). However, `initUsers` function do not seem to pick them up. Only after the operator is restarted, it seems to work.
Essential change 1: Make cluster's PgTeamMap a pointer:
```
--- PgTeamMap                    pgteams.PostgresTeamMap
+++ PgTeamMap                    *pgteams.PostgresTeamMap
```
Essential change 2: Additional teams and members are only fetched if the feature is enabled and the PgTeamMap is not `nil`
=> making pgTeamMap a pointer

pkg/apis/acid.zalan.do/v1/crds.go
This fixes the following error:
`error: error validating "test-manifest.yaml": error validating data: ValidationError(postgresql.spec.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0]): missing required field "preference, weight" in do.zalan.acid.v1.postgresql.spec.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution; if you choose to ignore these errors, turn validation off with --validate=false
`
where `test-manifest.yaml` is:
```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
name: test-manifest-cluster
namespace: default
spec:
teamId: "test"
volume:
size: 10Gi
numberOfInstances: 1
users:
test: []
databases:
test: test
nodeAffinity:
preferredDuringSchedulingIgnoredDuringExecution:
- weight: 1
preference:
matchExpressions:
- key: …
```
=> fix issue with soft node affinity CRD

e2e/tests/test_e2e.py, manifests/configmap.yaml, manifests/minimal-postgres-manifest-12.yaml, mocks/mocks.go, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/majorversionupgrade.go, pkg/cluster/pod.go, pkg/cluster/sync.go, pkg/controller/postgresql.go, pkg/controller/util_test.go, pkg/util/config/config.go, pkg/util/httpclient/httpclient.go, pkg/util/patroni/patroni.go, pkg/util/patroni/patroni_test.go
This PR introduces support to upgrade major version via manifest for a healthy cluster.
This PR also introduces the ability to configure a minimum and desired Postgres major version for all clusters. Clusters with smaller versions will automatically be upgraded to the respective target version, which is 13 for the time being.
=> Support major version upgrade via manifest and global upgrades via min version

pkg/cluster/sync.go
fixes https://github.com/zalando/postgres-operator/issues/1420
I can see the default privileges now.
I don't see how to easily test this, maybe the preparedDatabases feature needs some e2e tests?
=> create global default privileges in the appropriate prepared databases

charts/postgres-operator-ui/templates/deployment.yaml, charts/postgres-operator-ui/values.yaml
Parameterize TEAMS list in postgres-operator-ui Helm chart, as described in https://github.com/zalando/postgres-operator/issues/1373
=> [UI] Parameterize TEAMS list

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values-crd.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/k8sres.go, pkg/controller/operator_config.go, pkg/util/config/config.go
=> Fix for AllowPrivilegeEscalation : issue-1403

pkg/cluster/connection_pooler.go
Pooler deployment is updated on each sync:
```
time="2021-04-08T16:55:56Z" level=info msg="Update connection pooler deployment acid-minimal-cluster-pooler, reason: [pooler user is different (having pooler.acid-minimal-cluster.credentials.postgresql.acid.zalan.do, required pooler)]" cluster-name=default/acid-minimal-cluster pkg=cluster
```
The message is a bit confusing because it's the secrets which are compared. The current code uses `deployment.ClusterName` which is (or can be?) empty, hence producing a reason to update the deployment on every sync. The solution suggested in this PR is to use the `Name` field of the cluster. Thus, making `needSyncConnectionPoolerDefaults` a cluster method.
=> fix pooler sync with empty cluster name

pkg/cluster/cluster.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/sync_test.go
fixes #1447 
with `v1.6.2` we moved the rolling update flag from statefulset to pods. Thus, after bumping the operator version during the next sync there will be a difference between the current and generated statefulset. If this is the only difference the statefulset is patched. But in K8s one cannot remove things with `Patch`. It requires an `Update` to do so. To avoid extending the cluster rbac, we can choose to replace the statefulset if annotations are different.
In fact, our code does not even patch the statefulset if annotations for the new statefulset are [empty](https://github.com/zalando/postgres-operator/blob/0745ce7cce63ab6431103d27eb08e54ec47d2b15/pkg/cluster/resources.go#L200).
The annotation update in [Sync.go](https://github.com/zalando/postgres-operator/blob/0745ce7cce63ab …
=> replace statefulset on annotation diff

pkg/cluster/cluster.go
=> Synchronize statefulSet when modifying additionalVolumes

pkg/cluster/k8sres.go
=> Mount additional volumes to 'postgres' container when 'targetContains` is an empty list

pkg/cluster/exec.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/util/constants/kubernetes.go
In some code parts we assume that containers[0] is the postgres container. #1381 has shown that this might not always be the case. This PR tries to eliminate every code with that assumption.
=> get postgres container by name, not index

pkg/cluster/cluster.go, pkg/cluster/exec.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/cluster/sync.go, pkg/cluster/util.go
with #1504 we stopped assuming the first container being the postgres container. Hower, to avoid breaking things, bring back the old behavior as a fallback. Plus, some more refactoring.
=> pick first container if postgres is not found

pkg/cluster/pod.go
Operator should retry switchovers  before giving up on  moving master pods from non-ready nodes.
That is currently not the case: operator attempts to move the master pods once and then leaves them as is, thereby potentially blocking k8s cluster-wide processes such as node rotation.  With retries we avoid some of the blocking, namely the  cases where a replica was moved shortly before the master and is not ready at the time of the first switchover attempt of the operator.
To test,  build  and start operator and one PG cluster in `kind` as normal. Then:
1.  Tag the  replica pod  with the `nofailover` tag
```bash
kubectl exec -it $(kubectl get pods -l spilo-role=replica -o jsonpath={.items[0].metadata.name}) -- su postgres
echo -e "tags:\n nofailover: true" >> postgres.yml
patronictl reload …
```
=> Add basic retry around switchover

e2e/tests/test_e2e.py, pkg/cluster/sync.go
and simplify e2e test for cross namespace secrets.
Removed codelines have become obsolete, because the username will always contain the namespace at this point. At some stage of #1490 we've extracted the user from the full namespace-qualified name, hence making it necessary to add the namespace here. But, as of now, it would result in an error, because the namespace would be appended again (after the username, which seems strange, too). The name of the corresponding e2e test is changed, too, to be executed sooner and not at the end (which led to overseeing this bug).
=> fix searching for users with namespace in name

charts/postgres-operator/crds/postgresqls.yaml, e2e/tests/k8s_api.py, e2e/tests/test_e2e.py, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/cluster/sync.go
e2e test are executed in alphabetical order. Because it is sometimes important in which state the cluster is left after one test, it improves understanding and debugging when all test in the e2e file also following the alphabetical sorting.
Plus, this PR fixes alphabetical sorting of nodeAffinity in crd validation
=> reorder e2e tests to follow alphabetical sorting

charts/postgres-operator/crds/postgresqls.yaml, docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, docs/user.md, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/cluster/cluster.go
fixes #1580 
introduces a small addition to `preparedDatabases` to allow secrets of default LOGIN roles in other namespaces
=> allow secrets of default users in a different namespace

charts/postgres-operator-ui/templates/deployment.yaml, charts/postgres-operator-ui/values.yaml, ui/manifests/deployment.yaml
This PR allows adding any needed extra anv vars to the operator-ui deployment into the helm chart.
Fixes #1523
=> feat: Add extraEnvs to operator-ui helm chart

pkg/cluster/k8sres.go
Because this is more polluting the logs than helping.
=> remove debug log of Spilo env vars

pkg/cluster/connection_pooler.go
=> Support affinity and toleration in connection pooler deployments

charts/postgres-operator/templates/_helpers.tpl
As reported by @StepanKuksenko in https://github.com/zalando/postgres-operator/pull/1224#issuecomment-909247065, some properties are missing in the ConfigMap generated by the Helm chart.
This is due to the strict check on `if or (kindIs "string" $value) (kindIs "int" $value)`, whereas the list of variable types encountered by the function is `string`, `map`, `slice`, `bool` and `float64` (see that the last 2 are missing in `flattenValuesForConfigMap`.
My proposal is to actually use a `else` fallback, instead of explicitly looking for certain types.
(The alternative would be to expand/modify the list of type if the first `if` to include `bool` and `float64`.
Question: how can we prevent this kind of problem from happening again the future? Is there an integration that could be expanded?
=> Helm chart generates incomplete ConfigMap

manifests/complete-postgres-manifest.yaml
The ports section should be a list. Without this fix  you'll trigger the following error:
```
Warning  Create  2m38s  postgres-operator  json: cannot unmarshal object into Go struct field Sidecar.spec.sidecars.ports of type []v1.ContainerPort
```
=> Fix malformed YAML in the manifest

pkg/util/httpclient/httpclient.go, pkg/util/volumes/volumes.go
Fixes https://github.com/zalando/postgres-operator/issues/1614
The meaning of $PWD for "go generate" seems to have changed in go 1.17 .
See https://go-review.googlesource.com/c/go/+/287152
In go 1.16 this was the package folder and in go 1.17 it is the folder of the current file.
Using a relative path works in both go versions.
=> Fix mock generation in go 1.17

docs/administrator.md
I have found some typos in `docs/administrator.md` while trying out the physical backup feature.  `manifests/configmap.yaml` refers the credential as `pgsql-*-creds` even though they are defined as `psql-*-creds`.
My 2c.
=> docs: fix typos in credential names

docker/logical-backup/dump.sh
Sometimes the `head -n` pipe in the logical backup script (when getting the cluster host ip), causes SIGPIPE which will cause the script to exit with code 141, since `head` will only read the first line and cause a SIGPIPE signal to `jq`. I added an extra pipe to `tee` to resolve this issue.
=> Fix logical backup script sigpipe problem

docs/user.md, pkg/cluster/cluster.go
If enable_cross_namespaced_secret is set then emit log messages that the created username is with the namespace.
fixes #1684
=> Add log messages for usernames

docs/administrator.md
Current documentation in the postgres-operator fails to mention that WALG_AZ_PREFIX enables Azure Backups. This is a simple fix for the documentation so others won't be stranded.
Spilo image env variables: (https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst)
=> Adds required Azure backup env variable WALG_AZ_PREFIX to documentation

charts/postgres-operator-ui/values.yaml
`idendependent` -> `independent`
=> Fix typo on postgres-operator-ui values

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/crds/postgresqls.yaml, charts/postgres-operator/crds/postgresteams.yaml, charts/postgres-operator/templates/crds.yaml, charts/postgres-operator/values.yaml
Fixes #1677 
Let me know if I have missed to update some doc or similar somewhere.
=> Remove helm2 support from helm chart

charts/postgres-operator/templates/user-facing-clusterroles.yaml, charts/postgres-operator/values.yaml, docs/administrator.md
To allow the usage of the [aggregate ClusterRoles](https://github.com/zalando/postgres-operator/blob/master/manifests/user-facing-clusterroles.yaml), an option in the Helm chart is added.
Fixes https://github.com/zalando/postgres-operator/issues/1668
=> Add user facing ClusterRoles to Helm chart

pkg/controller/controller.go
=> Operator fails with nil pointer dereference when CR validation is not passed

pkg/cluster/connection_pooler.go, pkg/cluster/resources.go, pkg/cluster/sync_test.go, pkg/cluster/volumes.go, pkg/controller/util.go, pkg/controller/util_test.go, pkg/util/users/users.go
1. In different places we are collecting errors in an array. It should be initialized correctly with make.
2. Minor refactoring in `patroni_test` 
3. fixes #1681
=> Initialize arrays of errors / error messages + minor refactoring

pkg/cluster/majorversionupgrade.go
fixes looping over pods to get the master before performing the major version upgrade. If replicas come later `masterPod` can become a replica because of `= &pod`
=> make sure upgrade script runs on the master

charts/postgres-operator/crds/postgresqls.yaml, docs/reference/cluster_manifest.md, docs/user.md, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/cluster/k8sres.go
This allows standby clusters to be created from a GCS bucket by specifying either `gs_wal_path` with a full manual path, or `cluster` and optionally `uid` and `version` for similar behaviour to cloning. I've updated the documentation with the details. I have tested it against a number of GCS WAL-G backups and it seems to work nicely. I haven't tested the cluster-based replication from S3 as I don't have any data in S3 to try it out with.
It uses the main `GCPCredentials` from the operator config rather than requiring a standby-specific setting which I think should generally work. If different credentials are needed for pushing WALs then they can be changed at the same time as the standby is promoted.
I created this before I realised there was an existing PR! Let me know if it's useful. …
=> Support standby replication from GS (GCS)

e2e/tests/test_e2e.py, pkg/cluster/pod.go, pkg/cluster/sync.go
In #1341 we moved the rolling update flag from statefulset to single pods. From there on the list of pods to recreate was gathered in `syncStatefulset` which was then passed to `recreatedPods`. Our `isSafeToRecreatePods` [check](https://github.com/zalando/postgres-operator/blob/a78a619e909a1c64d4917bf6a426bcaff18dbc39/pkg/cluster/pod.go#L427) within `recreatePods` only examined the pods to recreate.
This could lead to a situation demonstrated in #1765. A change in resources leads to unschedulable instances. The rolling updates times out, but on next sync the operator will continue with the other instances that [have the update flag](https://github.com/zalando/postgres-operator/blob/a78a619e909a1c64d4917bf6a426bcaff18dbc39/pkg/cluster/sync.go#L319).
The log lines from the issue make the …
=> do not recreate pods if previous Patroni API calls fail

docs/administrator.md, e2e/tests/test_e2e.py, manifests/complete-postgres-manifest.yaml, pkg/cluster/sync.go, pkg/cluster/sync_test.go
1. When the next rotation date is set the period should be added to the current time, not to the time in the secret. In case the timestamp in the secret would be very old, it would need a few unnecessary rotations until we reach the current time.
2. The timestamp in the secret should also store the timestamp. We can just use Go's time.RFC3339 constant and do not worry about the format. As location we hardcode to UTC.
3. The complete manifest was giving wrong examples for password rotation options.
=> minor fixes to password rotation

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go
This PR makes the comparison of containers' ports a bit smarter: it takes into account default protocol (TCP) and ignores different ports order.
Fixes #1384.
=> Compare container ports in a smarter way

docs/developer.md, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
See https://github.com/zalando/postgres-operator/issues/1776.
Not sure if this is how you would want this implemented, but it didn't take long so I thought I'd get the conversation going. It's unclear to me how retries here might play into retries at higher levels.
Should the interval or timeout be configurable? Should it retry indefinitely?
=> Retry when getting the pod_environment_secret

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/pod.go, pkg/cluster/pod_test.go, pkg/controller/operator_config.go, pkg/util/config/config.go
add a new parameter for Patroni API timeout (PatroniAPICheckInterval, PatroniAPICheckTimeout)
=> Patroni API timeout

pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/apis/acid.zalan.do/v1/util_test.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
In Go, when a struct field is not set, it becomes a struct with
default values for all fields. These default values are included
during serialization. This causes issues with schema validation
where optional fields cannot be omitted because default values
are considered invalid.
This patch addresses this issue for `Resources` fields on several
types by using a pointer value.
=> Fix empty resources spec field failing schema validation

ui/app/src/edit.tag.pug, ui/app/src/help-general.tag.pug, ui/app/src/new.tag.pug, ui/app/src/postgresqls.tag.pug, ui/manifests/deployment.yaml, ui/operator_ui/main.py, ui/run_local.sh
Since AWS introduced gp3 volumes it became convenient to configure IOPS and throughput separately. Cost calculation is updated accordingly.
This PR also fixes the issues that resources and the postgres version could not be changed in the edit mode of the UI.
fixes #1620
=> [UI] support Postgres version, pod resource changes and IOPS + throughput config options

manifests/minimal-master-replica-svcmonitor.yaml
Signed-off-by: aisuko <urakiny@gmail.com>
Thanks for your guys did this awesome job and I already know the scope of Operator from issue #264 
So, I'd like to add the manifest as an example for end-user who like me just want to separate to monitor the `master` and `replica` of `pg-sql`, but there no more documents exist about this.
Finally, I'd like to help to contribute more examples like this about how to use the `pg-operator` more simply and professionally.
=> Add the minimal master/replica svc-monitor example manifest for end user

pkg/cluster/cluster.go
This PR disable create endpoins when option `kubernetes_use_configmaps` set to true.
I did not change RBAC, the operator works correctly with existing rules
```
- verbs:
- get
apiGroups:
- ''
resources:
- endpoints
```
and also works without them
Tested on OpenShift 4.6.
Fix #1740, Fix #1758
=> do not create endpoints when use config maps

docker/logical-backup/dump.sh
When you run the backup script inside a K8s which is DualStack and prefers IPv6 the api requests are failing.
Check if the IP address is v4 or v6 and add brackets accordingly.
=> Added IPv6 support for K8s API Service.

charts/postgres-operator/templates/clusterrole-postgres-pod.yaml, docs/quickstart.md, e2e/tests/test_e2e.py, manifests/configmap.yaml, manifests/operator-service-account-rbac-openshift.yaml, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/types.go, pkg/controller/postgresql.go, pkg/util/patroni/patroni.go, pkg/util/patroni/patroni_test.go
With #1760 merged, we should add a readinessProbe to the statefultSet because the ConfigMaps option defines a selector on the master service. Label selectors incl. readiness probes. We will add it either way.
#1760 also introduced a new suffix for deleting Patroni cluster objects which will result in an error for the new "leader" suffix if endpoints are used. Instead, the operator should just l log a warning and try to delete as much as it can. Another bug was introduced by not deleting all services if endpoints are used.
Other changes:
- user variables when specifying container ports
- check configmaps option when syncing ClusterStatus not omit endpoints
- remove endpoints from RBAC (provide RBAC manifest for OpenShift)
=> define readinessProbe on statefulSet

pkg/cluster/cluster.go, pkg/cluster/streams.go, pkg/cluster/streams_test.go
The delete code was still reflecting an earlier state of #1570 where only one event stream resource was possible per cluster. In fact, there can now exists multiple as per application ID. This PR introduces a cluster field to store those IDs to loop over them after cluster deletion.
=> Fix deletion of event streams resources

pkg/cluster/majorversionupgrade.go
We tested the solution in 3 places 
1. Openshift (with reduced perms)
2. AWS (with access runAsNonRoot: false )
3. Pure Vanila k8s
At this stage, we cannot change spilo image instead. 
Reason: PGO does not call a wrapper shell script (sh), but directly the python process. If it were a shell, we could have added this logic there. But now, it's too late, and only place to do it at this time is PGO.
The solution is conditionally applying solution of #1689 when root-less
=> major version upgrade for rootless and ocp : solving #1689

docs/user.md, manifests/complete-postgres-manifest.yaml
=> add chapter about restoring in place

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/user.md, manifests/configmap.yaml, manifests/minimal-fake-pooler-deployment.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml
Fixes #1750 
We changed auth_type in our pgBouncer image from `plain` to `md5`. According to pgBouncer [docs](https://www.pgbouncer.org/config.html#authentication-settings) if "md5 is configured and a user has a SCRAM secret, then SCRAM authentication is used automatically instead."
Added a paragraph how one can configure using secrets with `scram-sha-256` hashing.
=> bump pooler image with pgBouncer 1.17.0 and auth_type md5

charts/postgres-operator/crds/postgresqls.yaml, docs/administrator.md, manifests/complete-postgres-manifest.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
Fixes #1566
Closes #1209
Closes #1422
Closes #907
Closes #1807
Please pay attention, that this PR implementing an individual `[]EnvVar` option to the cluster CR and has higher priority to the cluster `pod_environment_secret` and `pod_environment_configmap` options.
TODO (after approach approve)
=> Ability to set pod environment variables on cluster resource

docs/administrator.md, docs/reference/operator_parameters.md, docs/user.md, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
Do everything related to env var of DB pods inside `GenerateSpiloPodEnvVars` and extend unit tests. Plus, I shuffled around unit tests in k8sres_test so that tests covering the same topics are next to each other.
incl. fix for setting cron_admin when there's only one owner to grant it to
=> refactor spilo env var generation

charts/postgres-operator/crds/postgresqls.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go
=> sync CRD with example manifests

docs/reference/operator_parameters.md, e2e/tests/test_e2e.py, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go, pkg/cluster/sync.go, pkg/spec/types.go, pkg/util/users/users.go
While it can also be useful to grant roles to all database owners our intention with #1805 was actually the opposite.
This PR reverts a couple of changes done in #1805 like introducing a `RoleOriginSpilo` role type. Do not create a pgUser for additional owner roles - it's enough to add them in the `memberOf` field of existing DB owners. In case somebody already started using this feature, the operator will handle the reversed membership and revoke additional roles from database owners again. The latter is implemented as part of `ExecuteSyncRequests`. When altering membership of db owners fails (e.g. because of the wrong membership):
1. check for matches between additional owners and database owner's groups (`memberOf`)
2. try to revoke database owner from additional owner role. The latter …
=> reverse membership for additional owner roles

ui/operator_ui/main.py
get_teams_for_user might return an empty list which would leave team and cluster_name unbound:
```
2022-04-28 07:38:23,972 ERROR: Exception on /operator/clusters/default/foobar-minimal-cluster/logs [GET]
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/operator_ui/main.py", line …
```
=> [UI] use safe defaults for fetching cluster logs

pkg/cluster/pod.go, pkg/util/patroni/patroni.go, pkg/util/patroni/patroni_test.go, pkg/util/util.go
fixes #1890
using a custom `uint64` type with its own `UnmarshalJSON` method
=> use uint64 for replication lag from Patroni's member endpoint

pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
In #1848 setting the clone bucket prefix env variable was mistakenly removed.
=> bring back CLONE_WAL_BUCKET_SCOPE_PREFIX

charts/postgres-operator/crds/postgresqls.yaml, manifests/postgresql.crd.yaml
Replaces 'DoesNotExists' with 'DoesNotExist'. Fixes #1868.
=> Fix a typo in the CRD yaml files.

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/controller/operator_config.go, pkg/util/config/config.go
In some situations it might be desired to scale beyond globally configured instance limits for single clusters.
The idea is to toggle this via an annotation in the cluster manifest. Just like with delete protection the key name is configurable. It is empty by default which also disables the feature.
When set, users have to add the annotation with value "true" to ignore the configured instance limits.
=> annotation to bypass globally configured instance limits

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, docs/user.md, manifests/operatorconfiguration.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go
We have forgotten to introduce the `mixed` storage resize mode in the OperatorConfiguration CRD. The docs on volume resizing were also a bit outdated.
Fixes #1946
=> add storage_resize_mode mixed to opConfig CRD

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, manifests/configmap.yaml, manifests/minimal-fake-pooler-deployment.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/cluster/k8sres.go
fixes #1511 
master-24 comes with alpine 3.15 base image
The PR also sets a safe default for PGHOST env variable in case serviceAddress does not find a service. When the deployment is created with empty PGHOST, connections will not work (`WARNING DNS lookup failed` and `pooler error: server login has been failing, try again later (server_login_retry)`) and the operator has no sync code to repair it because the pod template is not compared.
=> bump pooler image to use new alpine base image

pkg/cluster/pod.go
Change1: MigrateMasterPod now use getSwitchOverCandidate to select a new masterCandidate
Change2: Removed unused masterCandidate (replaced by getSwitchOverCandidate)
Fixes: #1983
=> BugFix: Switchover (during a Node drain) fails randomly in synchronous mode

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, docs/user.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/marshal.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/apis/acid.zalan.do/v1/util.go, pkg/apis/acid.zalan.do/v1/util_test.go, pkg/cluster/util.go, pkg/controller/operator_config.go, pkg/controller/postgresql.go, pkg/util/config/config.go
Teams of cluster change. Although the name of the cluster is immutable, it would still be helpful to change teamId field without the need to create a PostgresTeam resource.
On start up the operator calls `add_cluster` for all Postgresql resource it finds. When the new `enable_team_id_clustername_prefix` is enabled and cluster name does not start with team ID, `add_cluster` will return an error message and the cluster is not added to the operator's internal cluster list.
The Postgresql resource itself still gets created via K8s API. We have no controller in between to block this. Because the resource is there we can patch it's `PostgresClusterStatus` field in status subresource to `invalid`. Each sync on the cluster will try to call add_cluster again because it does not exist in the …
=> Make teamId in cluster name optional

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/connection_pooler.go, pkg/cluster/k8sres.go, pkg/cluster/streams_test.go, pkg/cluster/sync.go, pkg/util/constants/roles.go
If somebody unintentionally defines reserved system users `pooler` or `fes_user` in the manifest, the [updateSecret](https://github.com/zalando/postgres-operator/blob/e11edcdcde897ec16e6a9903f97a6cad2e96eee2/pkg/cluster/sync.go#L720) function will use the systemUsers map. But if the pooler or stream feature are not used, no corresponding PgUser object will exist in that map. The PgUser used in password rotation will be empty ultimatly leading to this error:
```
could not sync roles: error executing sync statements: could not execute sync requests for users: could not create user "": pq: zero-length delimited identifier at or near """"
```
The bug was introduced with #1953 .
=> fetch pooler and fes_user system user only when corresponding features are used

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, docs/user.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go, pkg/cluster/util.go, pkg/controller/postgresql.go, pkg/util/config/config.go
With #2001 merged we dropped the teamId prefix constraint for cluster names and deprecated the `ClusterName` field of the `Postgresql` type assuming it was not used somewhere else. Turns out, it is used for LoadBalancer service's external DNS name and ClusterStatus API.
This PR will set this field again when clusters are added to the operator's internal cluster list.
If we would continue to use the Spec.ClusterName for the LB DNS names they would break when disabling the team Id constraint. Therefore, we should continue to use old format when the cluster name starts with the team ID. external-dns supports multiple names per annotation, separated by comma.
=> use old LB DNS format when teamId prefix is disabled

manifests/fake-teams-api.yaml, pkg/cluster/sync.go, pkg/cluster/sync_test.go
The `updateSecret` code was using wrong keys when treating pooler and FES users accidentally adding more empty `cluster.systemUsers` leading to a similar error like in #2009 
I have extended the unit test for `updateSecret` to cover it.
=> use correct keys in updateSecret

pkg/cluster/streams.go, pkg/cluster/sync.go, pkg/cluster/sync_test.go
When `streams` are specified in the manifest the operator updates the Postgres config and starts creating DB publications and stream CRDs. The stream operator will notice the CRDs and start with creating deployments to consume from logical slots. But it will find the Postgres config not yet updated and crash a few times until the operator restarts the Pods on next sync.
When we know that instances must be restarted in `syncPostgresConfig` we could call Patroni's restart endpoint. But it would happen anyway when the statefulset is synced. Therfore, we can just quit `syncStreams` and wait for it.
=> create streams only after postgres instances were restarted

e2e/Dockerfile, e2e/Makefile, e2e/exec_into_env.sh, e2e/requirements.txt, e2e/run.sh, e2e/tests/k8s_api.py, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/types.go, pkg/cluster/util.go, pkg/cluster/util_test.go, pkg/util/k8sutil/k8sutil.go
PodDisruptionBudget API `v1beta1` is deprecated since K8s v 1.21 and is removed starting from v 1.25.
Note, with this change the Postgres Operator will not work for users on K8s 1.20 and lower.
closes #1999
=> switch to policy API v1 for PDBs

.github/workflows/run_e2e.yaml, e2e/tests/test_e2e.py, pkg/cluster/database.go, pkg/cluster/sync.go, pkg/util/users/users.go, pkg/util/util_test.go
#1953 introduced a bug in the user sync code. An extra pgUserMap [newUsers](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/sync.go#L942) was added to include systemUsers when passed to ProduceSyncRequests function. The info if a user is deprecated is overridden after newUsers variable is created, but only stored in the cluster's pgUsers variable.
Thus, ProduceSyncRequests does not know which users can be considered deprecated. The following bug can now happen:
1. Team members are marked as deprecated when they appear in the [pgUsersCache](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/sync.go#L932) but do not exist in desired c.pgUsers. This works.
2. Team members can re-join the team and the operator should rename the user back and grant LOGIN …
=> fix team member deprecation

e2e/tests/test_e2e.py, pkg/cluster/sync.go, pkg/cluster/sync_test.go
How it looks like without rotation
1. [initUsers](https://github.com/zalando/postgres-operator/blob/d209612b18122ae42250bd0517533fd7cbad5c66/pkg/cluster/cluster.go#L196): Generates list of desired users (manifest roles, system users, team members etc.) with new [random passwords](https://github.com/zalando/postgres-operator/blob/d209612b18122ae42250bd0517533fd7cbad5c66/pkg/cluster/cluster.go#L1302)
2. [syncSecrets](https://github.com/zalando/postgres-operator/blob/d209612b18122ae42250bd0517533fd7cbad5c66/pkg/cluster/sync.go#L628)
a. [generateUserSecrets](https://github.com/zalando/postgres-operator/blob/d209612b18122ae42250bd0517533fd7cbad5c66/pkg/cluster/k8sres.go#L1669): Generates a list of secrets where `username` and `password` in secret are taken from the …
=> Fix password rotation

docs/reference/operator_parameters.md
This code block was wrongly rendered in docs:
@moduon MT-1248
=> docs: fix code block rendering

pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
Fixes #2025 
Env variables shouldn't get from the `Cluster.Spec` structure
=> Cluster env variables should be reflected for StatefulSet update

docs/administrator.md
in the OperatorConfiguration CRD  "pod_environment_secret" and "pod_environment_configmap" properties is located under "kubernetes" object. aws_or_gcp object does not have these properties.
=> fix azure setup in administrator docs

pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
fixes #2031
I think the refactor in https://github.com/zalando/postgres-operator/pull/1848 has introduced this regression, do you think it was intended?
Before the refactor,  `getPodEnvironmentSecretVariables` and `getPodEnvironmentConfigMapVariables` were called directly in `generateStatefulSet` and we used to return an error (and halt the sync) instead of just logging the error and continue sync with missing data.
Maybe add a test and adjust documentation somewhere.
=> return error when Kube API is down during statefulset sync

docker/DebugDockerfile, docker/Dockerfile, ui/Dockerfile
Hello,
our SNYK security scan has found, that the Zalando Postgres Operator image is vulnerable to the following security issue which comes by using the Alpine 3.12 base image.
It should be fixed in Alpine 3.13. I would like to ask you to update the used base image of the Zalando Operator and release a new version.
https://www.cve.org/CVERecord?id=CVE-2022-37434
=> bumped to alpine base image 3.15

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/connection_pooler.go, pkg/cluster/sync.go
During UPDATE events initUsers can fail leading to a wrong c.pgUsers list and user syncing.
On SNYC events we [bail out immediately](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/sync.go#L51), however on UPDATE we carry on syncing everything we can. While it makes sense to sync K8s objects (stateful set, PDB, cron job) we better skip the database parts.
This PR also refactors small parts to better decide if initUsers is needed during UPDATE in the first place. For example, only do it if connectionPooler has been enabled or pooler user has changed. The stream user has been overlooked so far.
=> skip db sync on failed initUsers during UPDATE

pkg/cluster/streams.go
If tables for streams are not found in the database (maybe because of a typo in the table name) the publication sync will fail. The operator only returns a warning and continues to create the logical replication slot. This leads to the same error that #2085 already tried to solve. Even when creation of publications succeeds in future sync cycles, Postgres will return an error that they do not exist because the slots have been created before.
This PR suggests to only sync slots where publication sync succeeded.
=> skip slots where publication sync failed

docs/index.md
The Flant blog was rebranded as Palark & moved there. Updating a link to the related article accordingly.
=> fix: Update Flant blog link in docs

charts/postgres-operator/templates/operatorconfiguration.yaml
using tpl in value objects containing arrays allows us to override objects in arrays. This is not possible via helm --set due to limitations in helm
fixes #2114 together with #1986
=> use tpl in value objects containing arrays

manifests/e2e-storage-class.yaml, manifests/fake-teams-api.yaml, manifests/infrastructure-roles-new.yaml, manifests/infrastructure-roles.yaml, manifests/minimal-postgres-manifest-12.yaml, manifests/minimal-postgres-manifest.yaml, manifests/platform-credentials.yaml, manifests/postgresql-operator-default-configuration.yaml, manifests/standby-manifest.yaml
This PR fix some typos and remove predefined namespaces from the example manifests:
- Remove ns from the `StorageClass` (cluster wide resource)
- Fix duplicating `apiVersion` and `data` sections for `ConfigMap`
- Remove `default` ns from the CR's to allows deployment to any ns without modificatios
- Comment `patroni` section inside the default `OperatorConfiguration` as it's required field
=> Remove namespace and fix errors in example manifests files

README.md, charts/postgres-operator-ui/templates/deployment.yaml, charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/crds/postgresqls.yaml, charts/postgres-operator/values.yaml, docker/logical-backup/Dockerfile, docs/administrator.md, docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, docs/user.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/apis/acid.zalan.do/v1/util_test.go, pkg/cluster/k8sres_test.go, pkg/cluster/majorversionupgrade.go, pkg/controller/operator_config.go, pkg/util/config/config.go, ui/manifests/deployment.yaml, ui/operator_ui/main.py, ui/operator_ui/spiloutils.py, ui/run_local.sh
=> enable operator support for pg15 and drop support for 9.5 and 9.6

pkg/cluster/streams.go
Bugfix for feature merged with #2137. To avoid the following error:
```
level=error msg="could not sync cluster: could not sync streams: failed creating event streams with applicationId test-app: FabricEventStream.zalando.org \"acid-minimal-cluster-oKwZV\" is invalid: metadata.name: Invalid value: \"acid-minimal-cluster-oKwZV\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" cluster-name=default/acid-minimal-cluster pkg=controller worker=0
```
=> stream resource name must be lower case

pkg/cluster/streams.go, pkg/cluster/streams_test.go
With #2137 merged, stream CRD names are no longer known beforehand and, therefore, can only be listed using a label selector. The check if a stream CRD does exist and can be updated now happens within a loop over all fetched CRDs. If found that loop is exited - however NOT the loop over application Ids which handles creation of stream CRDs.
This means, stream CRDs are now created on each sync which succeeds because the name now has a random suffix. An extra bool flag is needed per application Id iteration to avoid that.
Unit tests were extended to cover this case.
=> fix syncing of stream CRDs

pkg/apis/acid.zalan.do/v1/postgresql_type.go
If you import the zalando postgresql v1 api with kubebuilder, it complains about the missing tags.
```
❯ make manifests
test -s /.../bin/controller-gen && /.../bin/controller-gen --version | grep -q v0.10.0 || \
GOBIN=/.../bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
/.../bin/controller-gen rbac:roleName=manager-role crd:allowDangerousTypes=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/.../go/pkg/mod/github.com/zalando/postgres-operator@v1.8.2/pkg/apis/acid.zalan.do/v1/postgresql_type.go:116:2: encountered struct field "Everyday" without JSON tag in type "MaintenanceWindow"
/.../go/pkg/mod/github.com/zalando/postgres-operator@v1.8.2/pkg/apis/acid.zalan.do/v1/postgresql_type.go:117:2: encountered struct field "Weekday" without JSON tag …
```
=> fix: add missing json tags to the MaintenanceWindow type struct.

docs/reference/cluster_manifest.md
The documentation incorrectly states the parameter name as `data-checksum` instead of `data-checksums`.
Signed-off-by: Stephan Austermühle <au@hcsd.de>
=> Fix parameter name for data-checksums

e2e/tests/test_e2e.py, pkg/cluster/cluster.go, pkg/cluster/sync.go, pkg/cluster/sync_test.go, pkg/util/patroni/patroni.go
Users can [specify replication slots](https://github.com/zalando/postgres-operator/blob/master/manifests/complete-postgres-manifest.yaml#L122) in the Postgres manifest and they are [added](https://github.com/zalando/postgres-operator/blob/4786f53f033154009051c2b1dc300be48c55790a/pkg/cluster/sync.go#L572) to the database via [Patroni REST API](https://github.com/zalando/postgres-operator/blob/4786f53f033154009051c2b1dc300be48c55790a/pkg/cluster/sync.go#L628). When the slot is removed from the manifest, it won't get deleted in the database. Here we follow the convention of the operator never dropping database objects because manifest edits could have been wrong accidentally.
However, with logical replication slots the situation is a little different. If they are not used, diskspace will …
=> Allow drop slots when it gets deleted from the manifest

docs/administrator.md, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
Follow up to #1976 but only changes the order for spec.Env overriding variables that would be set when clone or standby section exist. The later still takes precedence over values from global pod_environment_secret/configmap.
=> spec.env can override clone and standby variables

charts/postgres-operator/templates/deployment.yaml, charts/postgres-operator/values.yaml, pkg/apiserver/apiserver.go, pkg/controller/controller.go
=> Add operator deployment readiness probe

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, manifests/configmap.yaml, manifests/minimal-fake-pooler-deployment.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/cluster/connection_pooler.go
This pull request is heavily inspired by [this PR](https://github.com/zalando/postgres-operator/pull/1232) by @borchero and try to solve [#1230](https://github.com/zalando/postgres-operator/issues/1230)  But do not include the additional annotations on the pgBouncer deployment.
The entrypoint.sh in pgbouncer docker image also need to be updated to use the certificates when present like so:
``` bash
if [ -z "${CONNECTION_POOLER_CLIENT_TLS_CRT}" ]; then
openssl req -nodes -new -x509 -subj /CN=spilo.dummy.org \
-keyout /etc/ssl/certs/pgbouncer.key \
-out /etc/ssl/certs/pgbouncer.crt
else
ln ${CONNECTION_POOLER_CLIENT_TLS_CRT} /etc/ssl/certs/pgbouncer.crt
ln ${CONNECTION_POOLER_CLIENT_TLS_KEY} /etc/ssl/certs/pgbouncer.key
fi
```
however the dockerfile of pgbouncer included in the operator …
=> Add Support for Custom TLS Certificates in Connection Pooler

hack/update-codegen.sh, pkg/cluster/connection_pooler.go
Ineffectual assignment of the envVars for connection pooler if `spec.TLS` is specified.
@FxKu please have a look at this bug and try to fit it into the 1.9 if possible
Test case can be added, but this case should be covered by the linter
=> Ineffectual assignment of the envVars for connection pooler

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/administrator.md, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/cluster/cluster_test.go, pkg/cluster/util.go, pkg/controller/operator_config.go, pkg/util/config/config.go
With #2011 we changed the default DNS name format template used when LoadBalancers are enabled. For backwards compatibility we are already appending a second DNS entry when the cluster name still starts with the team Id (mandatory before #2001), because we do not want to break existing connections.
For the old format we only assumed the default template value `"{cluster}.{team}.{hostedzone}"`. There's no option to specify what you have used before. If you have customized the template, all apps would need to be redeployed using the new DNS format. To avoid such a hassle this PR suggest to make the old format configurable with `master|replica_old_dns_name_format` options.
The unit test in cluster_test_go has be updated to also use a template different from the default value.
=> better backwards compatibility with old DNS name format for LBs

pkg/cluster/sync.go
Password rotation should not be allowed for standby clusters because rotation users cannot be added anyway.
This is particularly helpful if the source clusters has no rotation enabled (e.g. is not maintained by Postgres Operator).
However, if the secrets are updated for the source cluster, then credentials must be synced manually - like during the initial setup of a standby.
=> do not rotate secrets for standby clusters

ui/operator_ui/main.py
The default memory and CPU that currently showing does not reflect the defined values in the environment variable.
=> UI: fix default cpu memory

pkg/cluster/streams.go, pkg/cluster/sync.go
The current flow when adding streams in the manifest is as follows:
SNYC 1:
1. [List Pods] `syncStatefulSet` compares desired (manifest) and effective Patroni config and restarts pods
2. [List Pods] `syncStreams` (calling `syncPostgresConfig`) sets `wal_level: logical` which requires a Postgres restart only happening in `syncStatefulSet`, exit `syncStreams` early
SNYC 2:
1. [List Pods] `syncStatefulSet` compares desired (manifest) and effective Patroni config and restarts pods
2. [List Pods] `syncStreams` (calling `syncPostgresConfig`) sets `wal_level: logical` but config is already updated - no restart required anymore, proceed with publications and slots
3. [List Pods] `syncStreams` (calling `syncPostgresConfig`) syncing replication slots in Patroni config
The PR proposes the following …
=> set wal_level for streams in statefulSet sync

docs/administrator.md, e2e/tests/test_e2e.py, manifests/complete-postgres-manifest.yaml, pkg/cluster/connection_pooler.go, pkg/cluster/k8sres.go, pkg/cluster/util.go, pkg/util/constants/pooler.go
fixes #2180 
Introduced two new functions: `generatePoolerServiceAnnotations` for the DNS annotation used for LBs and `getCustomServiceAnnotations` which is shared for all services. Because pooler unit tests need quite some refactoring, the annotations are tested in e2e suite.
Functions `masterDNSName` and `replicaDNSName` now take the cluster name as argument, to make them reusable for pooler DNS name resolving
=> add pooler suffix to DNS annotation of pooler LoadBalancer service

pkg/cluster/sync.go
`syncStatefulSet` and `syncStreams` both call `checkAndSetGlobalPostgreSQLConfiguration` to compare desired and effective Patroni config. Usually desired is what's specified in the manifest.
`syncStreams` however uses the config patch code to create logical replication slots that are not specified in the manifest. These slots then get added to [cluster.replicationSlots](https://github.com/zalando/postgres-operator/blob/d5251c5fc848e425258fe298655fc27cbd4035d0/pkg/cluster/sync.go#L650) (only on UPDATE events changing streams). This variable was introduced in #2089 to detect the removal of slots from the manifest. It should only contain slots specified in the manifest.
On the next SYNC `syncStatefulSet` will only compare manifest with effective config. The Postgres Operator goes over …
=> fix sync of stream slots

docs/administrator.md
This PR resolves https://github.com/zalando/postgres-operator/issues/1995.
It turns out it is already possible to use Workload Identity for authentication when using GCP for cluster backups. This PR adds an explanation of how to set this up.
=> chore(docs): add workload identity authentication to Google Cloud Platform backup setup

pkg/cluster/sync.go
Turns out on operator restart existing slots are not added by the [Create code](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/cluster.go#L379). I have mistaken ADD events from the log to be calling that code. Only when new clusters are added with slots specified in the manifest they will be added (and dropped when removed).
Newly introduced slots will be added in the [sync code](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/sync.go#L643). But for existing slots the loop over is continued when there is no difference and therefore it is not added to c.replicationSlots. So whenever there happens an operator restart existing slots wont get synced and not be dropped if they are removed from the manifest.
=> add c.replicationSlots on sync

pkg/cluster/k8sres.go
not needed and only left over from e2e test debugging
=> remove debug log for generated env vars of logical backup

pkg/cluster/cluster.go
In #2187 the flow for configuring Postgres for streams was moved to syncStatefulSet, because it's the only place right now where we restart Postgres on config changes. The restart is required to set wal_level to `logical` before creating publications and replication slots.
However, syncStatefulSet is not executed during [Create](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/cluster.go#L244). Whem a new cluster is added with stream section we face the same error as before - creation of publication during syncStreams will fail because wal_level has not been adjusted, yet. It happens only during next SYNC when it's too late.
Therefore, this PR proposed to call syncStatefulSet inside Create method, if streams are defined.
In case the sync of statefulset will fail return …
=> sync stateful set when syncing streams during ADD event

README.md
I think, it's time we can remove the Spilo 12 paragraph from the readme.
Since it has been requested a few times e.g. in #2231
=> Provide support matrix with Pg and K8s version

pkg/cluster/connection_pooler.go
last PR #2216 checked and not work. added security context fsGroup for correct load tls cert from mounted volume
=> fix to pooler TLS support

pkg/cluster/sync.go
addresses #2198
For extensions it's possible they are dependent on one another. Thus, it could happen that syncing an extensions can fail because another extension listed in the manifest has not been installed yet. The go loop iterates in random order, so sometimes it might work but mostly it won't.
This PR tries to improve the sync of databases, prepared databases and schemas and extension. Taking the idea that is also used in other parts to collect error messages rather then erroring out immediately. In some places the loop must be continued.
=> continue syncing databases and extensions on err

charts/postgres-operator/values.yaml
In 30b612489a2a20d968262791857d1db1a85e0b36 this update was forgotten. It is needed for logical backups of postgres 15 clusters, as seen in https://github.com/zalando/postgres-operator/issues/1945#issuecomment-1425060560.
The default value documented is different to the one actually used: https://github.com/zalando/postgres-operator/blob/9973262b83507ccb16c097aef9ca56b35a1cbf4a/docs/reference/operator_parameters.md?plain=1#L753-L758
Fixes https://github.com/zalando/postgres-operator/issues/1945.
@moduon MT-1075
Thanks for submitting a pull request to the Postgres Operator project.
Please, ensure your contribution matches the following items:
=> fix: PG 15 backups working by default

pkg/cluster/pod.go, pkg/cluster/pod_test.go, pkg/cluster/sync.go
fixes #2276 
On a two node clusters when performing a rolling update, it turned out that the recreated replica is chosen as switchover target before Patroni assigns it the synchronous status. Therefore, the switchover will fail with the following error:
```
2023-03-30 16:05:24,606 INFO: Updating synchronous privilege temporarily from ['test-sync-mode-0'] to []
2023-03-30 16:05:24,653 INFO: Assigning synchronous standby status to []
server signaled
2023-03-30 16:05:24,828 INFO: no action. I am (test-sync-mode-1), the leader with the lock
2023-03-30 16:05:34,670 INFO: no action. I am (test-sync-mode-1), the leader with the lock
2023-03-30 16:05:42.106 UTC [36] LOG {ticks: 0, maint: 0, retry: 0}
2023-03-30 16:05:44,682 INFO: no action. I am (test-sync-mode-1), the leader with the lock …
```
=> in sync mode select only syncStandby as switchover candidate

pkg/cluster/k8sres.go
just a small finding during reading
=> fix: make map in generateUserSecrets with correct size

.github/workflows/publish_ghcr_image.yaml, .github/workflows/run_e2e.yaml, Makefile, docker/Dockerfile, docker/build_operator.sh
Refactor operator image build process to allow multi-arch builds
Add a pipeline to build and publish arm64/amd64 image in ghcr on every pushed tag
=> Add pipeline to publish ghcr multi-arch image

pkg/cluster/cluster.go
In `Create()` function, some errors not been check. It will cause cluster status to unexpected.
For example:
https://github.com/zalando/postgres-operator/blob/0e7beb5fe50920cef82ce6e908ac52a9feaa3aa0/pkg/cluster/cluster.go#L271-L273
=> Fix some errors be ignored

docker/logical-backup/dump.sh
This allows correctly connecting to the Kubernetes API when the service host is set as a hostname. This is at least the case on gardener.cloud . I'm running the patched version in production.
Related to #2047 which describes the same problem I had.
=> Interpret KUBERNETES_SERVICE_HOST as hostname if not parsed as IP address

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/templates/configmap.yaml, charts/postgres-operator/templates/operatorconfiguration.yaml, charts/postgres-operator/values.yaml, docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
There is an inconsistency in the naming of the global config option for Patroni's failsafe mode. `enable_patroni_failsafe_mode` in configmap and `failsafe_mode` in OpeartorConfiguration CRD. In #2297 we noticed that this option is still missing in the helm chart templates, but the difference in the naming would make it a bit harder to add it to the both configmap and CRD templates.
Therefore, this PR will change the name in the CRD to `enable_patroni_failsafe_mode` as well albeit being listed under the `patroni` key. It also adds documentation which was still missing in the config reference. As the next release will the first version to support failsafe_mode by default, I do not think this renaming would break the setups of people out there.
=> rename failsafe_mode option in opconfig CRD

docs/reference/cluster_manifest.md
In `Prepared Databases` section of the cluster manifest documentation,  
it says `defaultRoles` and `defaultUsers` are **both disabled** by default for prepared schemas.
But `defaultRoles` is actually enabled by default, thus this MR fixes it.
=> Fix the wrong default value description in cluster manifest

docs/index.md
The link to Daniel Westermann's post "Getting started with the Zalando Operator for PostgreSQL" is outdated. This PR updates the link.
=> Update the link to a post

pkg/cluster/database.go
After the ping function is called, it returns an EOF error. 
https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/database.go#L138-L141
```
conn, err = sql.Open("postgres", connstring)
if err == nil {
err = conn.Ping()
}
```
These if statements will be false.
https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/database.go#L143-L150
```
if err == nil {
return true, nil
}
if _, ok := err.(*net.OpError); ok {
c.logger.Warningf("could not connect to Postgres database: %v", err)
return false, nil
}
```
Then the func will return false, err.
https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/database.go#L157
```
return false, err
```
Take a look at the `Retry` function and `RetryWorker` function. …
=> Handle retry connect to Postgres when ping return EOF error.

charts/postgres-operator-ui/templates/ingress.yaml, charts/postgres-operator-ui/values.yaml, ui/manifests/deployment.yaml, ui/manifests/ingress.yaml, ui/operator_ui/main.py, ui/operator_ui/templates/index.html
Attempts to fix breaking change introduced by #2195 to fix #2302.
APP_URL is only needed for authentication endpoints `/login` and `/logout`. The rest is relative paths. No need to set `<base href="{{app_url}}">` in UI's index.html.
I also noticed that the ingress spec differs from what we use. Changed the `pathType` to `Prefix` and `paths` to `["/"]`. Still people need to set an existing host.
This PR also adds an example for `USE_AWS_INSTANCE_PROFILE` which the UI supports but we forgot to expose it. Closes #2381
=> [UI] revert index.html base url and provide USE_AWS_INSTANCE_PROFILE example

e2e/tests/test_e2e.py
With #2343 merged the e2e pipeline is not passing anymore. At the moment, I suspect that scaling down the cluster to one instance but only checking PVC count happens very quickly so that we run without replicas into the subsequent e2e test which leads to:
```
======================================================================
FAIL: test_resource_generation (test_e2e.EndToEndTestCase)
Lower resource limits below configured minimum and let operator fix it.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
return function(*args, **kwargs)
File "/tests/test_e2e.py", line 1275, in test_resource_generation …
```
=> on PVC when_scaled:retain check pod count, too

docs/user.md
add a little note about  underscores / '_'  in the manifest will be dash '-' in the k8s secrets.  
I wasted a bit long time looking for the correct user names..
=> Update prepared database section section with secret name info

docs/user.md
#2424 has been merged into the wrong branch. This PR does the same doc page as well but fixes some grammar errors.
=> add info on secret name for prepared users

docker/logical-backup/Dockerfile
At the moment logical backup step is failing in our pipeline. Lets go to ubuntu 22, remove 10 and add 16
=> bump ubuntu version in logical-backup Dockerfile

pkg/cluster/cluster_test.go, pkg/cluster/util.go
When one defines a `fes_user` in the manifest and has also `streams` defined, the database password of this user gets overridden. The secret, however, is not touched. Therefore, removing the user from the manifest immediately fixes the issue. 
I found that when initializing robot / manifest users the check for name collisions with already defined system users is only done for the configured `SuperUsername` and `ReplicationUsername` - not for e.g. pooler of stream user. I changed it now to a loop over all system users that are already initialized at this point (not in the unit test though). Because, if this check does not happen, somewhere done the line the database role picks up a new [random password](https://github.com/zalando/postgres-operator/blob/96077c47d64db54bdf60d7e1eefeea3dee6022 …
=> let isSystemUsername check all system users

charts/postgres-operator-ui/values.yaml, docs/administrator.md, ui/manifests/deployment.yaml
Similar to `WATCHED_NAMESPACE` for the operator itself, `*` is a valid option for the UI. Without it clusters in multiple namespaces - rather, those not in the `TARGET_NAMESPACE` - will not show in the UI. Which can be confusing for users.
Mentioned in: https://github.com/zalando/postgres-operator/issues/1373
=> Document that `*` can be used for UI `TARGET_NAMESPACE` option

pkg/cluster/cluster.go
- when the desired statefulset has different numbers of volume claim template with current cluster,  will be panic because of index out of range
- when got different numbers of volume claim template, maybe no need to compare details, after all, it need to be replaced already
issue: [[https://github.com/zalando/postgres-operator/issues/2492](https://github.com/zalando/postgres-operator/issues/2492)]
=> Fix VolumeClaimTemplates index out of range problem

pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
Hello, 
Fixing https://github.com/zalando/postgres-operator/issues/1834
1. Making sure InheritedLabels set in operator settings / cluster settings are added to backup job pod manifest.
2. Making sure InheritedAnnotations set in operator settings / cluster setting are added to backup job pod manifest.
The goal is to see backup job resources in ArgoCD.
=> Populating crd labels and annotations in logical backup job pod manifest

charts/postgres-operator/crds/postgresqls.yaml, docs/reference/cluster_manifest.md, docs/user.md, manifests/complete-postgres-manifest.yaml, manifests/minimal-postgres-manifest.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
This is a simple approach to these issues and just allows hugepages requests and limits to be specified in the CR for postgres container and eventual sidecars.
At the moment, it is not possible to use the operator on clusters with enabled hugepages support, because postgres detects and tries to use hugepages, but fails to allocate as the limit on containers defaults to zero. This PR allows specifying a little amount of hugepages to prevent postgres from crashing.
Closes #1788 and closes #1549
=> Add hugepages 2Mi and 1Gi fields to ResourceDescription and pass them to the statefulset

CODEOWNERS, MAINTAINERS
Add 'macedigital' to `CODEOWNERS` and `MAINTAINERS` files
I cannot contribute to the codebase nor to the project in a meaningful way at the moment.
Merging this PR should enable me to get notified on new issues and pull-requests for maintaining the project.
Thanks for submitting a pull request to the Postgres Operator project.
Please, ensure your contribution matches the following items:
=> chore: add "macedigital" as codeowner & maintainer

docs/reference/operator_parameters.md
not displayed correctly [here](https://postgres-operator.readthedocs.io/en/latest/reference/operator_parameters/)
=> fixed markdown formatting operator_parameters.md

docs/reference/operator_parameters.md, go.mod, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go
The `enable_finalizers` option added in #941 was still missing in the example manifests. I also felt I had to add two more sentences to its docs.
=> adding finalizer option in all manifests and rework its docs

charts/postgres-operator/templates/_helpers.tpl, charts/postgres-operator/templates/configmap.yaml, charts/postgres-operator/templates/operatorconfiguration.yaml, charts/postgres-operator/templates/postgres-pod-priority-class.yaml, charts/postgres-operator/values.yaml
Hello,
To solve this issue https://github.com/zalando/postgres-operator/issues/2441, I present a possible solution by adding flags to create the PriorityClass (or not) and to set the priority. In case of a use of an external priorityclass, only the name should be set.
=> Feat: add flags for podPriorityClassName to support external priorityclasses

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, manifests/configmap.yaml, manifests/minimal-fake-pooler-deployment.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml
closes #2516
Bumps pgBouncer not only to 1.21.0 but to the latest 1.22.0.
=> bump pooler image to pgBouncer 1.22.0

kubectl-pg/cmd/create.go, kubectl-pg/cmd/delete.go, kubectl-pg/cmd/update.go, pkg/cluster/pod_test.go, pkg/cluster/sync_test.go, pkg/spec/types.go, pkg/util/patroni/patroni.go, pkg/util/patroni/patroni_test.go
ioutil is deprecated since go 1.16. Time to remove it.
This is a follow up to #2480 
Thanks @testwill for bringing it up.
=> replace deprecated ioutil

charts/postgres-operator/crds/postgresqls.yaml, docs/administrator.md, docs/reference/cluster_manifest.md, e2e/tests/test_e2e.py, manifests/complete-postgres-manifest.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/cluster/sync.go, pkg/cluster/sync_test.go
closes #1994
Introducing another slice to define users that should be ignored from secret rotation when it's globally enabled.
=> allow users to opt out from globally enabled secret rotation

pkg/cluster/streams.go, pkg/cluster/streams_test.go
If streams were already used before the introduction of recovery in #2421 the operator will detect a diff because it sets recovery to `type: None` when it's not enabled. Using the `Update` endpoint results in the following error:
```
could not sync cluster: could not sync streams: failed updating event stream my-stream: FabricEventStream.zalando.org "my-stream" is invalid: spec.eventStreams[0].recovery.sink: Invalid value: "null": spec.eventStreams[0].recovery.sink in body must be of type object: "null"
```
The operator does not specify the sink when `type: None` but it's part of the [recovery struct](https://github.com/zalando/postgres-operator/blob/29ea863faf115396a3ca3184d3aa813f0a349030/pkg/apis/zalando.org/v1/fabriceventstream.go#L56) and will be `nil` (because of pointer type). The …
=> patch event stream CRD instead of update

pkg/cluster/resources.go
The finalizer will not get removed if there are any errors during the delete. But, it can happen on cluster creation that child resources never got created and, thus, are empty like c.StatefulSet, c.PodDisruptionBudget etc. If the operator considers this as an error it would never allow the removal of finalizers.
Instead, in all the delete function the operator should only log the fact that a child resource is missing and return with nil. This way finalizer removal and manifest deletion can happen.
=> do not block delete because of emtpy child resources

pkg/cluster/cluster.go, pkg/cluster/sync.go, pkg/util/k8sutil/k8sutil.go
[Four years ago](https://github.com/zalando/postgres-operator/commit/0c6655a22dffce9c2388e6ca6a69bc29c26e7c6b) I moved the `setStatus` code to the `k8sutil` package in order to update the status also in the `controller` scope and not only inside `cluster`. For this I removed the line `c.setSpec(newspec)` and left it to the caller to update Spec struct.
However, it was not reflected by all callers which leads to the situation that further `Update` calls during DELETE events (like removing the finalizer) can be blocked because
1. the `resourceVersion` is already higher that it what is stored in c.Spec, in case the status changed (e.g. Running -> UpdateFailed).
2. [Delete()](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/cluster.go#L1067) func is not calling c.setSpec …
=> update spec when updating status

pkg/cluster/sync.go, pkg/cluster/sync_test.go
You may want certain users to switch to in-place rotation, but the operator does not set the username when it branches to in-place rotation in the go code. Thus, the username would always stay the same. It needs an extra line `secret.Data["username"] = []byte(secretUsername)`. Another workaround could be to first opt out with the new option introduced with #2528 and add the user to in-place rotation list afterwards.
But, the operator could also be smart enough to detect when the desired username is not a rotation user and allow for immediate rotation. This is what this PR introduces.
It can also work the other way around when switching from in-place rotation to rotation with extra users, like:
```
if len(currentUsername) != len(expectedUsername) {
rotationModeChanged = true
```
Unlike …
=> change username in secret when switching rotation mode

docker/Dockerfile
As specified in the OpenContainers Annotations Spec: https://specs.opencontainers.org/image-spec/annotations/
---
Automated tooling which checks container registries for new tags might not be able to find release notes (this is often via source code/parsing a CHANGELOG file) since this is not included in the container registry. Adding this annotation will allow tooling to follow the link to the source code, and look for release notes there. The tooling can then include these release notes in e.g. PRs with container image version bumps.
Dependabot and Renovatebot both use this annotation for this purpose:
* Dependabot: https://github.blog/changelog/2023-04-13-dependabot-now-supports-fetching-release-notes-and-changelogs-for-docker-images/
* Renovatebot: …
=> chore(build): Add OCI label for container image source

pkg/cluster/sync.go
CRD support was added previously, but comparing desired SynchronousNodeCount to the actual patroni config was missing
=> Fix updating SynchronousNodeCount (#2552)

docs/reference/operator_parameters.md, pkg/cluster/cluster.go, pkg/cluster/sync.go, pkg/controller/postgresql.go
Yet another follow-up to adding finalizers on existing clusters. If you cancel the kubectl delete command the controller does not find the deletionTimestamp and keeps on syncing the cluster. Only after restarting the operator by removing the pod the timestamp gets picked up.
I wanted to repeat the experiment but the cluster recreation failed, but I could not see why. With the changes made in #2546 I'm no longer returning the actual error on cluster creation but overriding it with the error returned from setting the status. This is wrong and is fixed with this PR.
=> return create and sync error, not setStatus error

pkg/cluster/database.go
We should wrap error like:
https://github.com/zalando/postgres-operator/blob/a5663da64f7a94af8dde395852cb2cf309ae27bc/pkg/cluster/database.go#L537-L545
=> fix: db row close error be ignored

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, e2e/tests/test_e2e.py, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/cluster/resources.go, pkg/controller/operator_config.go, pkg/util/config/config.go
closes #2567
addresses #1074
A long wished for feature to stop operator from deleting PVCs. To avoid confusion with the new PVC retention policy feature added in #2343 for which I added the missing documentation.
=> add option to prevent PVC removal on cluster deletion

pkg/cluster/majorversionupgrade.go, pkg/cluster/pod_test.go, pkg/util/patroni/patroni_test.go
In newer Patroni versions the state for running replicas changes to `streaming` (or `in archive recovery`). The operator already reflects this but not everywhere. I've updated the unit tests.
=> reflect new replica states in unit tests

charts/postgres-operator/templates/_helpers.tpl
When using the `configTarget: "ConfigMap"` option, the rendered configmap fails to install due to 
```
line 52: mapping key "persistent_volume_claim_retention_policy" already defined at line 51
```
This is caused by the flatten helper adding the config option too early causing duplicate keys like these to be created:
```
persistent_volume_claim_retention_policy: "when_deleted:retain"
persistent_volume_claim_retention_policy: "when_deleted:retain,when_scaled:retain"
``` 
This pr fixes this issue.
=> Fix duplicate key issue when using configmap config target

charts/postgres-operator/crds/postgresqls.yaml, docs/reference/cluster_manifest.md, manifests/complete-postgres-manifest.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
So far, it's only possible to configure the retention globally, but different clusters might have different requirements. As usual the manifest setting will take precedence over the global config. I changed the env var generation slightly to only add variables needed for a given LogicalBackupProvider. A new unit test is covering the code changed/added with this PR.
=> add logical backup retention as manifest option

charts/postgres-operator/templates/operatorconfiguration.yaml
This allows one to specify go templates in every setting applied to the OperatorConfiguration. This in turn allows me to do something like this:
```yaml
global:
s3:
endpoint: https://s3.example.com
access_key_id: xxx
secret_access_key: xxx
bucket: xxx
postgres-operator:
configLogicalBackup:
logical_backup_s3_endpoint: '{{ .Values.global.s3.endpoint }}'
logical_backup_s3_access_key_id: '{{ .Values.global.s3.access_key_id }}'
logical_backup_s3_secret_access_key: '{{ .Values.global.s3.secret_access_key }}'
logical_backup_s3_bucket: '{{ .Values.global.s3.bucket }}'
some-other-chart:
some-other-key: '{{ .Values.global.s3.bucket }}'
```
I applied `tpl` to all keys, because even though I only required logical backup for my use case, I see no reason to not add this to all keys.
=> Apply template on all keys of operatorconfiguration

charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/reference/operator_parameters.md, e2e/tests/test_e2e.py, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/operator_configuration_type.go, pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go, pkg/cluster/cluster.go, pkg/controller/operator_config.go, pkg/util/config/config.go
This PR introduces a configuration option to provide a way to disable the **deletion** of Kubernetes **secrets**: `enable_secrets_deletion` (default `true`).
Ratio: see https://github.com/zalando/postgres-operator/issues/1736#issuecomment-1999567249
I think many people would love this feature. This also relates to #2579, which otherwise wouldn't make much sense, because attaching already-existing volumes to a brand new cluster doesn't work due to different secrets.
Inspired by #2579 (huge thanks to @FxKu)
=> Secrets deletion config

.github/ISSUE_TEMPLATE/postgres-operator-issue-template.md, charts/postgres-operator-ui/values.yaml, charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/values.yaml, docs/administrator.md, docs/reference/operator_parameters.md, manifests/configmap.yaml, manifests/operatorconfiguration.crd.yaml, manifests/postgres-operator.yaml, manifests/postgresql-operator-default-configuration.yaml, pkg/controller/operator_config.go, pkg/util/config/config.go, ui/manifests/deployment.yaml
Since 1.11.0 we're building ghcr images for UI and logical backup too. It's time to reflect this also in configuration, manifest examples and helm chart to avoid further questions about missing arm support.
closes #2630
=> switch to ghcr image in helm chart and examples

charts/postgres-operator/crds/postgresqls.yaml, docs/reference/cluster_manifest.md, manifests/complete-postgres-manifest.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/crds.go, pkg/apis/acid.zalan.do/v1/postgresql_type.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go
=> Add SubPathExpr option for additionalVolumes

charts/postgres-operator-ui/templates/deployment.yaml, charts/postgres-operator-ui/values.yaml
This PR is a simple update to the `postgres-operator-ui` chart allows the following scheduling constraints to the **`operator-ui`** pods:  
- `affinity`
-  `nodeSelector`
-  `tolerations`
- `priorityClassName`
To clarify, this change **only** affects the `operator-ui` pods themselves and isn't a change to the actual UI.
This has come up before in the following issues: 
https://github.com/zalando/postgres-operator/issues/1921
https://github.com/zalando/postgres-operator/issues/1885
=> Allow scheduling constraints for operator-ui pods

pkg/util/config/config.go
=> Fix (#2644) - Add json tags to InfrastructureRole struct

.gitignore, ui/.dockerignore, ui/Dockerfile, ui/Makefile
Node v14 is end-of-life and should no longer be used. Commit changes Makefile to pull in latest node-lts instead.
Also, use local temporary folder for storing npm generated files to workaround permission issue with old npm version, e.g. emitting these errors:
```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
```
Both changes should also fix issue https://github.com/zalando/postgres-operator/issues/2651
=> fix: use nodejs-lts image for building frontend code

.github/workflows/publish_ghcr_image.yaml
Changes:
- Change argument for Github Actions to use the same [official Python image][1] as the one used for building "postgres-operator-ui" since commit  d60b424d7957d715003d9e5597bd5b5d63b6e250.
- Align image version in Github Actions pipeline with assumed default version in Dockerfile, using latest [Alpine 3](https://hub.docker.com/_/alpine)
Should fix problem with `publish_ghcr_image` workflow. 
[1]: https://hub.docker.com/_/python
=> Align Docker images in ghcr pipeline with images assumed in Dockerfile

docker/DebugDockerfile, docker/Dockerfile
Install available updates alongside installation of packages to remove known vulnerabilities from images.
Example for issues in plain alpine:3 image (v3.20):
```sh
$ grype alpine:3
✔ Vulnerability DB                [updated]
✔ Loaded image                                                            alpine:3
✔ Parsed image                    sha256:1d34ffeaf190be23d3de5a8de0a436676b758f48f
✔ Cataloged contents              dac15f325cac528994a5efe78787cd03bdd796979bda52fd
├── ✔ Packages                        [14 packages]
├── ✔ File digests                    [77 files]
├── ✔ File metadata                   [77 locations]
└── ✔ Executables                     [17 executables]
✔ Scanned for vulnerabilities     [8 vulnerability matches]
├── by severity: 0 critical, 0 high, 6 medium, 0 low, 0 …
```
=> chore: update package dependencies when building image

delivery.yaml
Commit switches builder image to `cdp-runtime/go`, removing the need to install `go` manually.
Also, commit splits "build-postgres-operator" pipeline into 2 distinct steps.
1. Run unit tests based on locally checked out code including set up of dependencies and generated code.
2. Build Docker image if tests are successful
=> chore: simplify delivery-yaml for building operator

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/k8sres.go
The current operator has a small bug when syncing logical backup cronjobs because it considers containers with empty and nil volumeMounts to be different. We should probably check for other places where we have this false assumption of how DeepEqual works. But for now, this PR will only improve upon syncing additionalVolumes for containers.
=> improve logical backup comparison unit test and improve container sync

.github/workflows/publish_ghcr_image.yaml, .github/workflows/run_e2e.yaml, .github/workflows/run_tests.yaml, Makefile, README.md, docker/build_operator.sh
to close open vulnerabilities with current go version
=> bump go version to 1.22.5

e2e/tests/test_e2e.py, pkg/cluster/streams.go, pkg/cluster/streams_test.go
This pull request addresses two related issues regarding the stream section during publication and slot creation:
1. Conditional FES Resource Creation:
The FES (Fabric Event Stream) resource will no longer be created if the logical slot does not exist. Previously, there was a bug causing the FES resource to be created regardless of the existence of the logical slot. This was not the expected behavior because creating the FES resource would trigger the FES operator to create publications and slots if they were missing. If publication and slot creation were not possible (e.g., due to missing tables), it would result in failures.
2. Logical Slot Creation/Deletion Based on Publication Modification:
The logical slot will now only be created or deleted if the publication modification is …
=> stream: slot and FES should not be created if the publication creation fails

pkg/cluster/cluster.go, pkg/cluster/util_test.go
Required one change in the update logic because before the operator only synced on schedule changes during UPDATE events. Now it syncs always when logical backups are enabled.
=> extend inherited annotations unit test to include logical backup cron job

pkg/cluster/majorversionupgrade.go, pkg/cluster/streams.go, pkg/cluster/streams_test.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/cluster/util_test.go
in our internal e2e tests I found the following logs:
```
level=warning msg="database replication slots for streams with applicationId test-app not in sync, skipping event stream sync" 
level=warning msg="database replication slots for streams with applicationId test-app-2 not in sync, skipping event stream sync"
```
The stream with test-app-2 uses a slot with not existing schema and table hence the expected second log line. But the stream of the first app should be fine. I have extended and improved the TestHasSlotsInSync unit test but found no bugs. After adding a logger, I found the issue:
In #2704 we [removed](https://github.com/zalando/postgres-operator/pull/2704/files#diff-6592d6884b6c11bdc6a11828daa2592c9c23b29865c49a30a55f6be5c7602ff7L137) always setting a slot to sync in order …
=> fix sync streams and add diffs for annotations and owner references

charts/postgres-operator/crds/postgresqls.yaml, manifests/postgresql.crd.yaml, pkg/apis/acid.zalan.do/v1/util_test.go
Make it reflect the implementation
=> MaintenanceWindow CRD validation fix

pkg/cluster/cluster.go, pkg/cluster/connection_pooler.go, pkg/cluster/database.go, pkg/cluster/majorversionupgrade.go, pkg/cluster/pod.go, pkg/cluster/resources.go, pkg/cluster/streams.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/cluster/volumes.go, pkg/controller/postgresql.go
This PR started with a small fix of the logs for syncing the config service (endpoint vs service). There was no debug message for syncing it. While looking at the operator logs in UI I found a few more log lines which were unnecessarily using the info log level instead of debug.
I went through the code and found also debug lines which could in fact be info log lines because they happen during cluster updates. In general, syncing should only be on debug level, actual changes on info level (at least the lines explaining the diff and reporting successful update - intermediate steps can still be on debug level)
After all, most changes in this PR is changing from Debugf (and Debugln) to Debug function when no formatting is needed.
=> align sync and update logs

pkg/cluster/cluster_test.go, pkg/cluster/connection_pooler_test.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/cluster/streams.go, pkg/cluster/streams_test.go, pkg/cluster/sync_test.go, pkg/controller/util.go, pkg/controller/util_test.go, pkg/util/k8sutil/k8sutil.go
The amount of problems reported by the linter - mainly redundant type declarations - made it hard to see problems such as nil references and unused variables. With this PR merged no more problems should be reported - at least in VSCode
=> reflect linter feedback, remove unused argumnents and redundant type from arrays

pkg/cluster/majorversionupgrade.go
When operator (re)-start, `c.currentMajorVersion` will be 0. This value will be updated only if we execute `majorVersionUpgrade` until the part where we get the current version from the Patroni. In #2727, we skipped the part where we do update this value when a cluster have `last-major-upgrade-failure` annotation. Hence, this cluster will never update its `c.currentMajorVersion` after operator restarts and will always be 0. Our e2e test couldn't catch this as we test the `last-major-upgrade-failure` after doing some upgrades. 
**Solution**
We should only skip the upgrade of the failure upgrade only after we make sure that the recheck is done.
=> Bugfix: skip upgrade when failed annotation should happen after recheck version

go.mod, go.sum, pkg/cluster/majorversionupgrade.go
Don't fail major upgrade (don't set annotation) if replica(s) are not (yet) streaming or replication lag is too high
=> Add major upgrade prechecks

pkg/cluster/majorversionupgrade.go
otherwise it fails non-gracefully 
```
time="2024-10-15T09:37:25Z" level=debug msg="making GET http request: x" cluster-name=default/x-standby pkg=cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3a8 pc=0x14ffba2]
goroutine 161 [running]:
github.com/zalando/postgres-operator/pkg/util/patroni.apiURL(0x0)
/go/src/github.com/zalando/postgres-operator/pkg/util/patroni/patroni.go:67 +0x22
github.com/zalando/postgres-operator/pkg/util/patroni.(*Patroni).GetClusterMembers(0xc000010420, 0xc000b32720?)
/go/src/github.com/zalando/postgres-operator/pkg/util/patroni/patroni.go:291 +0x1f
github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).majorVersionUpgrade(0xc000983908) …
```
=> Skip major upgrade for standby clusters with warning

charts/postgres-operator/Chart.yaml, charts/postgres-operator/templates/deployment.yaml
This PR fixes a template error in `postgres-operator/deployment`.
If you want to use `extraEnvs` in `values.yaml`, the current indentation for `extraEnvs` causes the resulting `deployment.yaml` to break due to incorrect indentation.
The nindent value has been updated from `12` to `8`.
**Result with the old values.yaml (nindent 12):**
**Result with the new nindent set to 8:**
Bumped Chart.yaml version to 1.13.1 but I'm not sure if it's correct
=> fix(postgres-operator/deployment): Set 'nindent' to 8 for 'extraEnvs'

docs/reference/operator_parameters.md, pkg/cluster/cluster.go, pkg/cluster/resources.go, pkg/cluster/volumes.go, pkg/cluster/volumes_test.go
PVCs are the only resource which is not covered by OwnerReferences. We have observed that on cluster deletion operator can report that all PVCs have already been deleted, although they still exist. We believe that there might be a race condition with cluster fields such as Name and Namespace getting unset after cascaded deletion via OwnerReferences resulting in an empty list when [fetching PVCs to delete](https://github.com/zalando/postgres-operator/blob/002d0f94a1463c15500dbfa77ea42c48e5790e6b/pkg/cluster/volumes.go#L266) (labelSet function [using c.Name](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/util.go#L479) for filtering). PVC management by StatefulSet is set to Retain in our case.
This PR present an idea which we use for other resources as well: Storing …
=> add cluster field for PVCs

pkg/cluster/pod.go, pkg/cluster/pod_test.go
fixe [issue](https://github.com/zalando/postgres-operator/issues/2751).
When asynchronous mode is enabled and no candidates are found, no retry is currently triggered to fetch a switchover candidate from the Patroni API. This PR enables retry for asynchronous mode, similar to [synchronous mode](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/pod.go#L485-L486).
=> fix switch over candidate retrieving

pkg/cluster/streams.go, pkg/cluster/streams_test.go
#2733 fixed a bug with stream duplicates created on every operator restart. To facilitate the cleanup the operator was deleting every extra stream it found based on the filter labels.
In general, the operator should be careful with what it deletes. Therefore this PR removes the delete call again assuming that duplicates should not exist only if somebody adds them manually with the same labels which is unlikely to happen. Sorting is not supported in go client so we would not be able to tell which stream gets synced in the cluster struct (same for deletions).
I have split the update streams unit test to have a dedicated test only for removal.
=> remove streams delete and extend unit tests

e2e/tests/test_e2e.py, pkg/cluster/streams.go, pkg/cluster/streams_test.go
The annotation comparison for streams was not ready yet, for comparing new annotations. Only the current ones were copied to `desiredAnnotations`. This was not caught because unit test compared either different streams with different specs, and we did not compare the full reason string. By extending the latter, tests started failing.
After fixing the annotation comparison the stream generator function started failing because the current code did not set the resource annotation when they were missing before. Only when a value could be found for comparison (which is impossible when setting the annotation does not work, of course :zany_face: )
I refactored the code and created a new pass by reference function `setResourceAnnotation` so that the FES generation code remains readable.
=> fix comparing stream annotations and improve unit test

pkg/cluster/streams_test.go
in #2820 the stream comparison unit test got greatly improved and we added a comparison of expected versus returned reason. It turns out that the order or reported added or mismatching annotations is unpredictable. When we remove the memory setting from the unit test, the chances for differences should be minimized (maybe even impossible)
=> fix flaky stream comparison unit test of retruned errors

charts/postgres-operator/values.yaml
Update logical backup docker image frm `13.0` to `14.0` so backups also work with postgres 17
=> Update logical backup docker image

docs/administrator.md, docs/reference/cluster_manifest.md, e2e/tests/test_e2e.py, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/majorversionupgrade.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/util.go, pkg/cluster/util_test.go, pkg/controller/node.go, pkg/util/patroni/patroni.go
Consider maintenance window when migrating master pods and replacing pods (rolling update)
=> Extend MaintenanceWindows parameter usage

pkg/cluster/majorversionupgrade.go
This way we avoid misleading "skipping major version upgrade, not in maintenance window" log line when `c.currentMajorVersion` is not initialized (==0)
=> Only check maintenance window for upgrade after pg version recheck

docs/administrator.md, docs/reference/cluster_manifest.md, e2e/tests/test_e2e.py, pkg/cluster/cluster.go, pkg/cluster/pod.go, pkg/cluster/sync.go
Consider MaintenanceWindows only for pod migration
=> Partially revert #2810

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/connection_pooler.go, pkg/cluster/resources.go, pkg/cluster/streams.go, pkg/cluster/sync.go, pkg/cluster/sync_test.go, pkg/cluster/util_test.go, pkg/cluster/volumes.go
fix use case when an annotation is removed from the `podAnnotations` setting  (should be reflected for the running Pods and Pod templates)
=> Ensure podAnnotations are removed from pods if reset in the config

docs/administrator.md, docs/quickstart.md, docs/reference/operator_parameters.md, e2e/tests/test_e2e.py, pkg/cluster/cluster.go, pkg/cluster/k8sres.go, pkg/cluster/k8sres_test.go, pkg/cluster/resources.go, pkg/cluster/sync.go, pkg/cluster/types.go, pkg/cluster/util_test.go
Create the second PDB to cover Pods with a special "critical operation" label set.
This label is going to be assigned to all pg cluster's Pods by the Operator during a PG major version upgrade, by Patroni during a cluster/replica bootstrap. It can also be set manually or by any other automation tool.
=> Critical operation PDB

e2e/tests/test_e2e.py, pkg/cluster/cluster.go, pkg/cluster/k8sres.go
In #2657 a [bug](https://github.com/zalando/postgres-operator/commit/47efca33c9857b5ada5cade4051468170f8ff17a#diff-f4933755bd63c9e160a2068e8ccb4048e8df1b43f7f4544dcbc7ae2650a07478R975) was introduced which produces additional secrets for rotation users which are redundant to the original secret. Before syncing secrets we usually initialize the user list to get the desired state.
On UPDATE events we only needed to sync secrets in case the user setup changed. `initUsers` and `syncSecrets` were called in one if block. The behavior was changed to have to if blocks where secrets can be synced on annotations diff while skipping user initializing. Therefore, the current pgUser list is used which contains the rotation users instead of the original ones.
We better return to the previous behavior …
=> fix creating secrets for rotation users

charts/postgres-operator-ui/values.yaml, ui/manifests/deployment.yaml, ui/operator_ui/main.py, ui/operator_ui/spiloutils.py, ui/requirements.txt
This PR removes the usage of the deprecated and unmaintained wal-e Python library from the UI backend and replaces it fully with boto3. In addition to cleaning up the dependency, this change enhances the UI by supporting the display of backups created by both wal-e and wal-g in the "Backup" tab. Previously, the UI could only show backups from wal-e; with this update, backups from both tools are now properly listed and displayed.
Backup view returned when wal-g is used as a backup tool:
=> [UI] Remove deprecated WAL-E library and enable WAL-G backup support in UI backend

docs/administrator.md, docs/reference/cluster_manifest.md, docs/reference/operator_parameters.md, docs/user.md
Hi,
This is a trivial PR for fixing some spelling issues found by [codespell](https://github.com/codespell-project/codespell).
=> docs: Fix issues found by codespell
